### ISSUE TITLE
关于富文本

### ISSUE THREAD

**Issue by ShareChou** [liangliangyy/DjangoBlog#115]
我想把富文本编辑器换成kindeditor再完善它，但是当我给ArticlelAdmin添加类后，后台文章那一部分就不能正常访问了，我想把现有的富文本修改一下，却死活找不到入口，不知道从哪里下手。

**Comment by liangliangyy** [comment]
现在后台是用markdown作为编辑器的,位置在 DjangoBlog/blog/admin.py

```python
class ArticleForm(forms.ModelForm):
    body = forms.CharField(widget=AdminPagedownWidget())

    class Meta:
        model = Article
        fields = '__all__'
```

所以如果你要改成别的编辑器,修改这里就可以了.
