### ISSUE TITLE
你好博主,很高兴,看到你的项目,这个项目是否有详细的,安装文档

### ISSUE THREAD

**Issue by qiubite-name** [liangliangyy/DjangoBlog#126]
你好博主,很高兴,看到你的项目,这个项目是否有详细的,安装文档

**Comment by liangliangyy** [comment]
非常感谢您对本项目的关注,暂时没有整理安装文档,不过您可以参考Readme的说明,将配置及数据库创建好,生产环境部署的话可以参考:
[使用Nginx+Gunicorn+virtualenv+supervisor来部署django项目](https://www.lylinux.org/%E4%BD%BF%E7%94%A8nginxgunicornvirtualenvsupervisor%E6%9D%A5%E9%83%A8%E7%BD%B2django%E9%A1%B9%E7%9B%AE.html)

**Comment by xiuyuanjun** [comment]
感觉README.md 写的就很清楚的啊！
