### ISSUE TITLE
项目运行后，css文件找不到

### ISSUE THREAD

**Issue by tm2018** [liangliangyy/DjangoBlog#135]
python版本：3.6.3
django版本：2.0+
系统版本：ubuntu16.04

你好！我git了你的项目，运行起来后，发现未加载到css和js文件，f12查看调试如图：
![image](https://user-images.githubusercontent.com/31844089/42501205-cb9235f2-8465-11e8-98eb-3ebe59045fcc.png)

我在其他界面，也会报错找不到js文件，在项目中根本未找到相关js和css，请问，我哪里出错了？该如何更改？

**Comment by xiaokai111** [comment]
如果你只是想看看网站效果，并用python manage runserver 的形式运行网站的话，在setting.py里面改成debug=True。就可以了。 如果是正式部署，比如用nginx部署的时候，将静态文件的目录在nginx配置文件里面配置好就可以了。

**Comment by liangliangyy** [comment]
#120 
#82 
#49
#15
