### ISSUE TITLE
创建数据库报错

### ISSUE THREAD

**Issue by AliceNEET** [liangliangyy/DjangoBlog#149]
![qq 20180730134640](https://user-images.githubusercontent.com/20288016/43379448-167fc3f6-93ff-11e8-9629-9a814e24e032.png)
运行python manage.py makemigrations报了这个错误
系统win10 64bit
已经运行过pip install -Ur requirement.txt且全部安装成功

**Comment by AliceNEET** [comment]
谢谢，问题没有出现了，但是希望在readme中加入一点，创建数据库的时候要在mysql中创建djangoblog数据库，而不只是运行命令。

**Comment by liangliangyy** [comment]
对.多谢提醒.这个我稍后在readme中加上.
