### ISSUE TITLE
runserver成功 ，服务器ip:8000 无法访问，阿里云端口是开了的

### ISSUE THREAD

**Issue by Sandry666** [liangliangyy/DjangoBlog#158]
![image](https://user-images.githubusercontent.com/30287824/45213007-efbacc00-b2c8-11e8-8d0c-91f64d667eb1.png)

**Comment by liangliangyy** [comment]
需要监听 0.0.0.0
```
./ manage.py runserver 0.0.0.0:8000
```

**Comment by Sandry666** [comment]
可以了Thanks
