### ISSUE TITLE
面包屑  导航首页链接拼接有问题

### ISSUE THREAD

**Issue by Sandry666** [liangliangyy/DjangoBlog#159]
![image](https://user-images.githubusercontent.com/30287824/45272684-4ef32900-b4e1-11e8-90ba-4eed93cc7907.png)
![qq20180910-100632](https://user-images.githubusercontent.com/30287824/45272696-5b778180-b4e1-11e8-829c-d5a1004aee7a.png)

**Comment by liangliangyy** [comment]
哇还真是...
我晚点修复下.多谢提醒.

**Comment by liangliangyy** [comment]
@Sandry666 已修复.
