### ISSUE TITLE
文章详情页/首页 响应时间长的问题

### ISSUE THREAD

**Issue by Sandry666** [liangliangyy/DjangoBlog#160]
点击文章标题进入详情页经常报错找不到页面，或者响应时间很长
报错如下
![image](https://user-images.githubusercontent.com/30287824/45272924-90380880-b4e2-11e8-8b3e-03c9951e9396.png)

**Comment by liangliangyy** [comment]
是 50x.html 这个路径找不到
为什么会跳到 50x.html 这个页面呢?

**Comment by Sandry666** [comment]
nginx 有这个配置 我已经给注释了 error_page   500 502 503 504  /50x.html 
我也不知道啥情况 经常502 www.bestdxc.com  大佬可以看看~   我这里read more 这些响应很慢
