### ISSUE TITLE
需要部署mem缓存吗？

### ISSUE THREAD

**Issue by cheyunhua** [liangliangyy/DjangoBlog#161]
您好车兄，我也姓车，不知道茫茫人海就能找个姓车的，而且还是同行

**Comment by liangliangyy** [comment]
哈哈哈, 我们姓车的人好少哎,能遇到也算是缘分.

部署最好还是加上mem缓存,这样可以提升响应速度.如果你没有部署memcache服务的话,可以参考readme中的配置部分,使用locmem缓存.
