### ISSUE TITLE
安装模块的时候报错，请问如何解决？

### ISSUE THREAD

**Issue by gaomengsuijia** [liangliangyy/DjangoBlog#163]
使用命令：
pip install -Ur requirements.txt
安装过程中报错如下：
![10](https://user-images.githubusercontent.com/15652704/45611151-f8618e00-ba90-11e8-9869-a8eff4a18101.png)

**Comment by liangliangyy** [comment]
你好,请参照输出说明,安装
Microsoft Visual C++ 14.0
