### ISSUE TITLE
请问数据库用SQLite可以吗

### ISSUE THREAD

**Issue by ChangeTheWorld** [liangliangyy/DjangoBlog#164]
文章数量不会太多，如果用SQLite跑起来大概什么地方会出瓶颈呢，谢谢。

**Comment by liangliangyy** [comment]
使用SQLite是可以的,建议注意备份好数据库文件.另外如果有缓存加持的话应该还可以接受.

**Comment by ChangeTheWorld** [comment]
缓存加持是指用 memcache 之类的么
