### ISSUE TITLE
大佬  我能不能参考你这个做个毕设

### ISSUE THREAD

**Issue by jy2lhz** [liangliangyy/DjangoBlog#171]
菜鸡  毕设选的网页设计  题目不限  但是没啥数据来源  查了查只有博客系统比较简单 。由于只会一点python  所以就搜了一下，了解了一点django，照着网上的教程搞了一下，发现好多不会  所以就来github搜了一下，准备参考一下您的自己实现一下。可以的话就谢谢了

**Comment by liangliangyy** [comment]
你好，你可以参考本博客，但具体功能请自己实现，本博客只能为你起到示例作用。

**Comment by jy2lhz** [comment]
好的 谢谢 老哥了  到时候会附上参考链接的
