### ISSUE TITLE
facebook登录

### ISSUE THREAD

**Issue by JunemShe** [liangliangyy/DjangoBlog#182]
您好，上周问过您，那个问题被关闭了，如果需要使用fb登录，项目必须放在外网服务器上而不是我连接外网吗？我拿到了code，但是拿去换token， requests这一步出现了 ConnectionError

**Comment by liangliangyy** [comment]
是这样的，根据code换取token的话是需要通过Facebook的api来获取的，所以你代码运行的环境需要能fq的。

**Comment by JunemShe** [comment]
了解了，thanks

**Comment by liangliangyy** [comment]
#179
