### ISSUE TITLE
老哥，有没有详细的那种教程步骤呀？

### ISSUE THREAD

**Issue by OMGkillerMao** [liangliangyy/DjangoBlog#183]
老哥，我是个新手，想学习写这个博客系统，你这个太复杂了，虽然运行出来了，但是里面的文件比较多，看的有点懵。。。

**Comment by liangliangyy** [comment]
抱歉，暂时还没有代码相关的文档，如果初学的话建议先阅读下官方文档的Getting started部分：
https://docs.djangoproject.com/en/2.1/intro/
这样会有一个整体的认识，后面再看代码就容易懂了。

**Comment by 0x0021** [comment]
大神，顺道问下  后台的布局怎么调整，要改哪些文件？

**Comment by liangliangyy** [comment]
在 `admin.py` 中
