### ISSUE TITLE
文章中怎么插入图片？

### ISSUE THREAD

**Issue by onsunsl** [liangliangyy/DjangoBlog#184]
`
 body = models.TextField('正文')
`
文章正文能不能使用UEditorField

另外， 怎么插入图片，图片只能是外链吗？

**Comment by liangliangyy** [comment]
你好. 文章是使用markdown的. 按照markdown的语法插入图片就可以了.

**Comment by onsunsl** [comment]
marddown我有了解，但是前提得先上传吧？怎么上传图片？

**Comment by liangliangyy** [comment]
是支持上传图片的，位置在 `DjangoBlog/blog/views.py`中 `fileupload` 方法，
但是需要你写调用代码来上传，如果不想写的话也可以使用别的图床工具来上传图片。
