### ISSUE TITLE
README.md 邮件地址错误？

### ISSUE THREAD

**Issue by 8solo** [liangliangyy/DjangoBlog#185]
HIIIIIIIIIIIIIIIIIII！
我来捣个蛋，道友，不对，Gi 友，你README.md 邮件地址是不是得改一下，强迫症看着难受。。。
确实是 # 不是 @liangliangyy  吗？
原文如下：

问题相关
有任何问题欢迎提Issue,或者将问题描述发送至我邮箱 liangliangyy#gmail.com.我会尽快解答.推荐提交Issue方式.

**Comment by liangliangyy** [comment]
阿哈，写成 # 是为了防止呗爬虫爬，然后收到一些乱七八糟的垃圾邮件。

**Comment by 8solo** [comment]
吆西,长知识了.谢了!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 车亮亮 <notifications@github.com>
发送时间: Monday, November 12, 2018 9:44:14 PM
收件人: liangliangyy/DjangoBlog
抄送: 8solo; Author
主题: Re: [liangliangyy/DjangoBlog] README.md 邮件地址错误？ (#185)


阿哈，写成 # 是为了防止呗爬虫爬，然后收到一些乱七八糟的垃圾邮件。

―
