### ISSUE TITLE
反射型XSS

### ISSUE THREAD

**Issue by ssstl** [liangliangyy/DjangoBlog#187]
您好，在我的开源项目检测中发现DjangoBlog存在跨站脚本：反射型XSS，详细信息如下：
![image](https://user-images.githubusercontent.com/26295946/49217041-7e8e3f00-f407-11e8-80cf-64108fae9f25.png)
![image](https://user-images.githubusercontent.com/26295946/49217320-36bbe780-f408-11e8-827e-30fa1843234b.png)

在oauth/views.py中第50行，在请求中获取了nexturl，在90/99行直接使用获取的数据进行跳转，将容易受到反射型XSS攻击。建议对输入和URL进行过滤，如：白名单和黑名单

**Comment by liangliangyy** [comment]
非常感谢您的提醒！我稍后会修复。
