### ISSUE TITLE
Centos 7 + apache2  部署

### ISSUE THREAD

**Issue by dbgns** [liangliangyy/DjangoBlog#191]
![image](https://user-images.githubusercontent.com/37951601/49684244-0cef7880-fb0c-11e8-8823-f7d8b01352f2.png)
请问这是什么错误啊...弄了一天实在没头绪

**Comment by dbgns** [comment]
我进一步定位了问题，是url_patterns里面，如果我把url_patterns = [] 一切正常，但是只要里面的项有了Include就不行了,

**Comment by dbgns** [comment]
然后 如果把文章全删除了会报 divison error

**Comment by liangliangyy** [comment]
是不是没有权限导致的？
代码要有`www-data`用户权限？

**Comment by dbgns** [comment]
好像是权限问题，但我不太懂这个....我里面没有www-data用户组，我的apache 应该用的user就是apache 吧？这样还需要创建www-data吗？还有就是我上面不知道为啥/usr/lib里的python会被加入到python path 里，但即使我把/usr/local/lib 和bin的所有者改成apache依旧不行(好吧，这个操作很2 )，还请大哥教教我啊，麻烦啦～

**Comment by liangliangyy** [comment]
我没用过apache来部署，你可以参考下我的这篇文章：
[使用Nginx+Gunicorn+virtualenv+supervisor来部署django项目](https://www.lylinux.org/%E4%BD%BF%E7%94%A8nginxgunicornvirtualenvsupervisor%E6%9D%A5%E9%83%A8%E7%BD%B2django%E9%A1%B9%E7%9B%AE.html)
apache使用的用户应该是在配置文件里面有的，可以在配置文件里面找下。
