### ISSUE TITLE
下载的链接打不开

### ISSUE THREAD

**Issue by LoveDoze** [liangliangyy/DjangoBlog#194]
博主，谢谢你的分享，想把你这个项目在本地运行 ，但是按照你说的pip install -Ur requirements.txt安装不了，点击链接也不下载

**Comment by liangliangyy** [comment]
你好，安装不了是有报错吗，请详细描述下。

**Comment by liangliangyy** [comment]
解决了就好，非常高兴我的项目能帮助到你~~
