### ISSUE TITLE
pip install -Ur requirements.txt出错 在windows

### ISSUE THREAD

**Issue by zhangxingye** [liangliangyy/DjangoBlog#195]
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by liangliangyy** [comment]
请安装 http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by zhangxingye** [comment]
get_current_site().domain 这个是获取根地址吗 他获取了example.com

**Comment by liangliangyy** [comment]
这个需要在后台 站点 修改下就可以了。
