### ISSUE TITLE
请问这个Blog项目是只能管理员账户在管理界面才可以添加文章吗?普通用户是否无法添加文章？

### ISSUE THREAD

**Issue by floatyun** [liangliangyy/DjangoBlog#215]
请问这个Blog项目是**只能管理员账户**在**管理界面**才可以添加文章吗?普通用户是否无法添加文章，只可以评论与回复？
另外管理员的添加文章是否是只能通过管理界面添加，**并未实现其它添加文章的前端接口**？

**Comment by liangliangyy** [comment]
是的。
