### ISSUE TITLE
请问如何上传本地图片到博文里面

### ISSUE THREAD

**Issue by PiercJ** [liangliangyy/DjangoBlog#216]
你好~请问如何上传本地图片到博文里面，编辑博文的时候好像没有找到这个选项，麻烦解答一下哈。

**Comment by liangliangyy** [comment]
你好，编辑博文那里没有提供上传图片的功能，不过有提供简单的图床功能，位置在：
https://github.com/liangliangyy/DjangoBlog/blob/98cfc508705234013a27fc9a7bee399abdbc5200/blog/views.py#L249  

你需要自己写一个上传工具来上传。

**Comment by PiercJ** [comment]
好的，谢谢哈

**Comment by liangliangyy** [comment]
这个issue我就不关了,有好多人都有这个问题.贴上面让大家都可以看到.

**Comment by liangliangyy** [comment]
#184

**Comment by PiercJ** [comment]
好的~基本上已经解决了，感谢哈

**Comment by scholarg** [comment]
你是图床功能和上传到本地功能都具备？

**Comment by liangliangyy** [comment]
@scholarg  @PiercJ 
请获取下最新版本代码，替换了后台markdown编辑器，支持图片上传了。

**Comment by PiercJ** [comment]
好~666~谢谢哈

**Comment by PiercJ** [comment]
你的网址~打开好像不能显示完整样式哦
