### ISSUE TITLE
简单的SEO功能，新建文章等会自动通知Google和百度

### ISSUE THREAD

**Issue by jren2019** [liangliangyy/DjangoBlog#217]
您好，

看到您说增加了会自动通知Google和百度这些功能，我不知道是哪些代码实现了这些功能，麻烦告知下具体是哪里实现的，把代码贴一个？我想学习一下这个。

万分感谢

**Comment by liangliangyy** [comment]
你好,位置在:
https://github.com/liangliangyy/DjangoBlog/blob/master/DjangoBlog/spider_notify.py
百度的话需要在其站长平台上注册.然后找到推送接口url.
谷歌需要你的服务器可以正常访问谷歌.
