### ISSUE TITLE
你好，请问在后台添加的分类，怎样控制显示排序？

### ISSUE THREAD

**Issue by PiercJ** [liangliangyy/DjangoBlog#218]
你好，我遇到一个问题，使用后台的时候，添加分类后，顺序不可控，有时候添加的分类排在前面，有时候又会排在后面，请问怎样控制呢？谢谢哈

**Comment by liangliangyy** [comment]
你说的顺序不可控是在什么位置显示的顺序呢? 前端菜单还是后台界面?
排序控制是在:
https://github.com/liangliangyy/DjangoBlog/blob/98cfc508705234013a27fc9a7bee399abdbc5200/blog/models.py#L145-L148

前端菜单显示是在:
https://github.com/liangliangyy/DjangoBlog/blob/98cfc508705234013a27fc9a7bee399abdbc5200/templates/share_layout/nav.html#L11-L14

**Comment by PiercJ** [comment]
好，谢谢哈，我参考一下。是这样的，在端显示，比如我用后台新建一个“关于“的分类，前端显示会放到第一个，我再新增一个“原来如此”分类，前段显示就会放到最后（在文章归档之前）。后台好像找不到控制分类标签显示顺序的地方。
