### ISSUE TITLE
如何替换后台富文本编辑器

### ISSUE THREAD

**Issue by PiercJ** [liangliangyy/DjangoBlog#220]
你好，最近我在使用后台发布文章的时候，觉得有点不方便，原因是我复制转载别人的文章的时候，别人页面的样式没有复制过来，这点我觉得有点不方便。所以就想把后台的文章编辑器，替换成百度开源的UEditor。请问替换现在的富文本编辑器，是写在哪个文件里面呢？我需要在哪个文件上做修改呢？谢谢哈

**Comment by liangliangyy** [comment]
https://www.google.com/search?q=UEditor+django&oq=UEditor+django

**Comment by liangliangyy** [comment]
https://github.com/liangliangyy/DjangoBlog/blob/98cfc508705234013a27fc9a7bee399abdbc5200/blog/admin.py#L29-L34

https://github.com/liangliangyy/DjangoBlog/blob/98cfc508705234013a27fc9a7bee399abdbc5200/blog/admin.py#L59-L70

**Comment by PiercJ** [comment]
好~谢谢哈，我找到UEdtor的django版本，分享一下https://github.com/dhcn/DUEditor
