### ISSUE TITLE
请问如何调整博客页面的宽度？

### ISSUE THREAD

**Issue by PiercJ** [liangliangyy/DjangoBlog#221]
你好，我想调整一下博客页面的宽度，和里面文章内容的宽度，请问是修改那个文件，怎么修改的呢？谢谢哈

**Comment by liangliangyy** [comment]
分别是在:
https://github.com/liangliangyy/DjangoBlog/blob/ae769f9d1d05b39ecce736deb4448c64984a9483/blog/static/blog/css/style.css#L1650-L1655
https://github.com/liangliangyy/DjangoBlog/blob/ae769f9d1d05b39ecce736deb4448c64984a9483/blog/static/blog/css/style.css#L1657-L1660

具体的话chrome F12看看吧

**Comment by PiercJ** [comment]
好~感谢，搞定了哈
