### ISSUE TITLE
我想让文章里显示一张本地的图片，应该怎么做？

### ISSUE THREAD

**Issue by zhangwujideshushu** [liangliangyy/DjangoBlog#224]
比如下面这张图怎么样在文章里显示出来？
/media/img/1.png

**Comment by liangliangyy** [comment]
你好. 请参考 #184  和 #216

**Comment by zhangwujideshushu** [comment]
1、自己写代码调用fileupload函数把图片上传到DjangoBlog/media/目录下。（小白不会写则看第2条）
2、自己写一个图片的models注册到admin，使用admin管理来上传图片到DjangoBlog/media/目录下。这样最多在数据库里多了图片的一些记录，如标题，路径等。（参考Django Web开发指南，里面有）
3、假如DjangoBlog/media/下有一个1.png，nginx.cnf 配置 location /media { alias /home/xxx/work/DjangoBlog/media; }，这样www.xxxx.com/media/1.png就是该图片的url。（nginx本身就是一个简易图床）
4、markdown插入改图片的url完美显示图片： www.hopemao.com

**Comment by liangliangyy** [comment]
@zhangwujideshushu 请获取下最新版本代码，替换了后台markdown编辑器，支持图片上传了。

**Comment by guocdfeifei** [comment]
> @zhangwujideshushu 请获取下最新版本代码，替换了后台markdown编辑器，支持图片上传了。

是那种支持黏贴版 图片自动上传的么？亲
