### ISSUE TITLE
数据库最大限制

### ISSUE THREAD

**Issue by 1009157211** [liangliangyy/DjangoBlog#225]
Index column size too large. The maximum column size is 767 bytes. 请问这个怎么解决

**Comment by 1009157211** [comment]
我尝试了百度的好多方法 都不行

**Comment by 1009157211** [comment]
./manage.py migrate  执行这段代码的时候出现的

**Comment by liangliangyy** [comment]
这个是字段超长了，你修改了model中某个字段的长度吗？

**Comment by 1009157211** [comment]
我按照教程一步一步走下去的  不知道为啥就超出字段了

**Comment by liangliangyy** [comment]
请列举下mysql的版本，以及更详细的错误信息。

**Comment by 1009157211** [comment]
mysql  Ver 14.14 Distrib 5.6.43, for Linux (x86_64) using  EditLine wrapper  数据库版本

django.db.utils.InternalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')  详细错误

**Comment by liangliangyy** [comment]
请参考：
https://stackoverflow.com/questions/30761867/mysql-error-the-maximum-column-size-is-767-bytes
