### ISSUE TITLE
pip install -Ur requirement.txt  报错

### ISSUE THREAD

**Issue by floatyun** [liangliangyy/DjangoBlog#238]
由于使用了U参数，报错如下：
django-compressor 2.2 has requirement rjsmin==1.0.12, but you'll have rjsmin 1.1.0 which is incompatible.
貌似只需要把rjsmin卸载掉，然后指定安装1.0.12版本，再重新安装django-compressor即可。建议修改首页readme.md中的"pip install -Ur requirement“,去掉U参数。

**Comment by Tender-Liu** [comment]
你好，请使用python得虚拟环境
$ cd /opt
$ python3.6 -m venv py3   #创建虚拟环境
$ source /opt/py3/bin/activate     #进入虚拟python环境
$ pip install -Ur requirements.txt   #安装依赖
$ deactivate  #退出虚拟环境
