### ISSUE TITLE
哈哈,  之前一直在寻找一个模板,  用过一段时间,  感觉风格有些简约,  后来换掉了,  还是很感谢.  可以看看我现在的  [ https://www.mongona.com](https://www.mongona.com "人生苦短, people like python").

### ISSUE THREAD

**Issue by zly7125839** [liangliangyy/DjangoBlog#241]
哈哈,  之前一直在寻找一个模板,  用过一段时间,  感觉风格有些简约,  后来换掉了,  还是很感谢.  可以看看我现在的  [ https://www.mongona.com](https://www.mongona.com "人生苦短, people like python").

_Originally posted by @x931890193 in https://github.com/liangliangyy/DjangoBlog/issues/214#issuecomment-468134732_

**Comment by liangliangyy** [comment]
你好，感谢回复，我移到了 #214 
这个issue我关闭了。

**Comment by Jimi2333** [comment]
@zly7125839 你好骚啊，bilibili代码学习笔记。。。。。

**Comment by hongzeyuan** [comment]
能指导下不，gunicorn 配置不成功，不知道什么原因~
