### ISSUE TITLE
504 time_out

### ISSUE THREAD

**Issue by fvaryu** [liangliangyy/DjangoBlog#248]
为什么我部署后时有时无的会504 Gateway Time-out
开始以为是nginx的问题Google后修改配置，还是会出现，而且详情比较多，打印日志发现视图层处理蛮快的
class ArticleDetailView(DetailView):
记录的输出

nginx error：
*122799 upstream timed out (110: Connection timed out) while reading response header from upstream,

猜测似乎是缓存的问题 记录加载时间那个中间件似乎 有时不返回。

 本地跑起来没有这个超时问题

**Comment by liangliangyy** [comment]
你是使用的本机内存缓存吗?
超时的时候网站是不是有别的异常?

**Comment by fvaryu** [comment]
@liangliangyy memcache  其他正常  cpu 内存 都正常 所以很奇怪 首页不会，多数出现在文章详情，

有时候调试第一次访问某个详情正常，第二次就会504，等几分钟又正常

**Comment by liangliangyy** [comment]
你的代码是最新的吗? 感觉有可能是 haystack自动更新索引的问题. 你获取下最新的代码然后再观察看看.

**Comment by fvaryu** [comment]
OK  我在试试看

**Comment by fvaryu** [comment]
莫名其妙的不出现了 尴尬
