### ISSUE TITLE
数据库中所有表的字段对应的含义

### ISSUE THREAD

**Issue by iPhone2018** [liangliangyy/DjangoBlog#251]
博主您好，请问数据库中所有表中对应的字段的含义是什么呢？然后我需要怎么添加对应的数据进去？因为我克隆了一份您的项目，但是运行后，发现界面没有任何图片和文字，我该怎么添加呢。自己是个基础小白，就学了点django，想要根据您的项目作参考，自己也尝试写一个，还望博主能够指导一下

**Comment by liangliangyy** [comment]
你好.可以在后台添加文章的. 访问 http://127.0.0.1:8000/admin
