### ISSUE TITLE
现版本是不是因为缓存经常会引起500错误

### ISSUE THREAD

**Issue by Half-SRE** [liangliangyy/DjangoBlog#257]
刚部署上试了几天，发现经常因为缓存引起500错误，点击”刷新缓存“后就OK了，尝试去了memcached缓存，这样子的话，整个网站就不可用了，一来因为我不是开发，Python仔细跟过去的话，也许能找到原因，二来这几天因为工作事情实在是没时间看，不知道是不是只有我存在这个问题呢

**Comment by Half-SRE** [comment]
_dict = self.func(*resolved_args, **resolved_kwargs)
  File "/data/codes/DjangoBlog/blog/templatetags/blog_tags.py", line 152, in load_sidebar
    count = sum(map(lambda t: t[1], s))
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by Half-SRE** [comment]
问题应该是t[1]取到了None,换一种方式count = sum([t[1] for t in s if t[1]])即可

**Comment by Half-SRE** [comment]
我就是个自学半吊子😂

**Comment by liangliangyy** [comment]
貌似和 #259  是一个问题. 我晚点看看.

**Comment by Half-SRE** [comment]
嗯嗯，我尝试改了下，添加了判断取值None，在用户登录的时候好像没什么问题了，退出后就不行了，坐等楼主修复，😝

**Comment by liangliangyy** [comment]
@Half-SRE 该问题已修复，请获取下最新代码。

**Comment by Half-SRE** [comment]
_dict = self.func(*resolved_args, **resolved_kwargs)
  File "/data/codes/DjangoBlog/blog/templatetags/blog_tags.py", line 151, in load_sidebar
    s = [t for t in [(t, t.get_article_count()) for t in tags] if t[1] > 0]
  File "/data/codes/DjangoBlog/blog/templatetags/blog_tags.py", line 151, in <listcomp>
    s = [t for t in [(t, t.get_article_count()) for t in tags] if t[1] > 0]
TypeError: '>' not supported between instances of 'str' and 'int'
点击"read more",还有一些标签仍然会有问题
