### ISSUE TITLE
标签关联文章总数为0会报错

### ISSUE THREAD

**Issue by Jimi2333** [liangliangyy/DjangoBlog#259]
![image](https://user-images.githubusercontent.com/30394875/57219536-fbfb5280-702a-11e9-8503-14e8daa70baf.png)

ZeroDivisionError at /  \DjangoBlog-master\blog\templatetags\blog_tags.py in <lambda>, line 155

任何文章关联到任意一个标签就不会报错了，
刚刚学python，语法不太懂，错误应该就是这里，请作者讲解下：

![image](https://user-images.githubusercontent.com/30394875/57219789-c99e2500-702b-11e9-9804-48bdfc948edd.png)

**Comment by liangliangyy** [comment]
感谢提醒.我晚点看看.

**Comment by liangliangyy** [comment]
@Jimi2333 已经修复，请获取最新代码。
