### ISSUE TITLE
请教oauth的问题

### ISSUE THREAD

**Issue by fvaryu** [liangliangyy/DjangoBlog#263]
我配置了微博的auth，审核也通过的，启用后会说回调地址不匹配
https://litets.com/auth/authorize这样配置的。

看了你的博客'http://www.lylinux.net/oauth/authorize?type=weibo&next_url=/'
我把地址改成了https://litets.com/auth/authorize?type=weibo，还是不行

最后把 url = self.AUTH_URL + "?" + "redirect_uri=" + self.callback_url + '&'+urllib.parse.urlencode(params)改成这样就可以了，  也就是不encode，但是为什么你的就可以呢？

还有如果是在评论取那里点击登录，完成后会回到首页，体验不是很好。

**Comment by liangliangyy** [comment]
你好，oauth这样配置就可以了
https://你的域名/oauth/authorize?type=weibo
登录时候会自动带上 redirect_uri的

**Comment by fvaryu** [comment]
@liangliangyy  我的URL encode后就不行 不知道为什么，  必须写成原始的才行
