### ISSUE TITLE
通过宝塔面板+uwsgi+centos+Nginx部署，访问静态文件403错误

### ISSUE THREAD

**Issue by istill1** [liangliangyy/DjangoBlog#270]
如题，项目中的setting反复检查了，没有错误。Nginx配置如下，不知是啥问题，请指教。

server {
  listen  80; #如有多个web应用，都是80端口监听
  server_name xxx.com; #域名地址
  
  location / {
    include      uwsgi_params;
    uwsgi_pass   127.0.0.1:8385;  # 指向uwsgi 所应用的内部地址,所有请求将转发给uwsgi 处理
    uwsgi_param UWSGI_PYHOME /root/virtualenvs/daikuan; # 指向虚拟环境目录
    uwsgi_param UWSGI_CHDIR  /www/wwwroot/daikuan.django; # 指向网站根目录
  }
  
  location /static/ {
          expires max;
          alias /root/daikuan.django/collectedstatic/;
    }

}

感谢作者的无私贡献。

**Comment by liangliangyy** [comment]
你好. 403是没权限吗? 还是你有别的规则给禁了?
宝塔面板我没用过. 你可以先试试在本地host是正常的吗?
