### ISSUE TITLE
get() returned more than one Category -- it returned 2!

### ISSUE THREAD

**Issue by halfsre** [liangliangyy/DjangoBlog#277]
get() returned more than one Category -- it returned 2!
我仅仅是更换了nginx版本，启用了http2，另外加了些nginx配置，启动后有个分类web,其下有子类nginx，就这个分类，点击返回错误，其他所有分类正常，还麻烦楼主抽空给看一眼，谢谢。

**Comment by halfsre** [comment]
好奇怪，测试发现，只要添加分类nginx就会出问题，看来nginx多传入一个值。

**Comment by liangliangyy** [comment]
你好，可以提供详细一点到信息吗？我这里没有复现。

**Comment by halfsre** [comment]
主要关联的view如下，
/data/codes/DjangoBlog/blog/views.py in get_queryset
        key = self.get_queryset_cache_key() 
/data/codes/DjangoBlog/blog/views.py in get_queryset_cache_key
        category = get_object_or_404(Category, slug=slug) 
最后，
/usr/local/lib/python3.6/site-packages/django/db/models/query.py in get
            (self.model._meta.object_name, num) 

Variable | Value
-- | --
args | ()
clone | <QuerySet [<Category: web>, <Category: nginx>]>
kwargs | {'slug': 'nginx'}
num | 2

**Comment by halfsre** [comment]
之前是nginx1.12是OK的，我升级到最新1.16后出了问题

**Comment by halfsre** [comment]
还有一点，无论nginx分类是不是web的子类，添加nignx分类后，web分类也会跟着出错，这两个字符串是不是有什么特殊性呢

**Comment by liangliangyy** [comment]
你是不是有两个名字是 nginx 的分类

**Comment by halfsre** [comment]
没有啊，楼主加个联系方式啊

**Comment by halfsre** [comment]
两个相同名字的分类是不能添加成功的，博主要不要开个QQ群呀

**Comment by halfsre** [comment]
哦，发现问题出在哪了，web分类的url为`https://www.halfsre.com/category/nginx.html`，应该是web.html啊

**Comment by liangliangyy** [comment]
是slug没更新. web分类你是直接修改的数据库吗?

**Comment by liangliangyy** [comment]
我知道了. 
https://github.com/liangliangyy/DjangoBlog/blob/master/blog/models.py#L34
这里有bug. 心塞.
我晚点修复下.

**Comment by halfsre** [comment]
我咋能整出这么些麻烦呢

**Comment by liangliangyy** [comment]
哈哈.不会不会.非常感谢你的反馈.

**Comment by liangliangyy** [comment]
#279 已修复。 @halfsre 
这个版本修改了mysql客户端，请查看readme中说明。
