### ISSUE TITLE
带注释的博客，还有想问问作者前辈Python web该怎么继续提升

### ISSUE THREAD

**Issue by enjoy-binbin** [liangliangyy/DjangoBlog#278]
临近毕业，最近自己的提升不大，大学学的知识有些杂，现在python-web算是比较熟悉，也自己写过博客、商场。

会使用很多类库、但是感觉对自己技术的深度提升不大。有在慢慢读一些开源系统和库的源码。

但是了解到python-web的方向比较窄，可能也是自己技术不够，而且现在也有点迷惘不知道该怎么进步了

所以想问下作者前辈以前那会是怎么继续提升的。或者web方面还有哪些方向可以继续提升

贴一个自己目前写过最好的一个项目，博客系统 /捂脸 写烂了的一个题材，中间有参考过很多开源博客，不过其中是看作者的收获最大，很久前当下来之后就一直看源码，学习到了很多

link: https://github.com/enjoy-binbin/Django-blog    借鉴了作者前辈的很多内容，不过我也自己写了很多注释，也自己在学习过程中继续开发，加了很多东西，这里很感谢前辈的分享，也希望能得到前辈的回复 😁

**Comment by liangliangyy** [comment]
你好，前辈真的不敢当，看到你是web方向，不知道你是偏向于前端方向还是后端方向，我自己接触更多的就是后端，所以针对后端说些自己的拙见来供你参考。
在熟悉了如django等web框架之后，可以关注下一些web端常见的解决方案和基础工具等，如高并发，高访问量的系统设计，锁，分布式等等。以及`redis`，`elasticsearch`,`zookeeper`等业界比较流行的工具或数据库，当你真正的进入之后你就会发现整个系统是非常庞杂并且需要学习的东西是非常多的。而这些东西你就可以在自己的业余项目中来尝试实现并使用，在这个过程中我相信一定会受益匪浅的。

**Comment by liangliangyy** [comment]
@enjoy-binbin 
这个issue我先关闭了，因为毕竟和本项目无关，后续可以邮件讨论。
