### ISSUE TITLE
The build fails on Python 3.7

### ISSUE THREAD

**Issue by cclauss** [liangliangyy/DjangoBlog#291]
https://travis-ci.org/liangliangyy/DjangoBlog/builds/554520750

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by liangliangyy** [comment]
#290 
i think this should because of the mysql character set.
