### ISSUE TITLE
'NoneType' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by ericsqxd** [liangliangyy/DjangoBlog#292]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

我遇到了一个问题，还希望楼主可以帮助一下
 ERROR [blog.templatetags.blog_tags.datetimeformat:56 blog_tags] 'NoneType' object has no attribute 'strftime'

**Comment by liangliangyy** [comment]
你是不是没有选择创建时间或者发布时间？

**Comment by chrismins** [comment]
遇到同样的问题，请问有解决吗？？？
