### ISSUE TITLE
可以写一个markdown上传图片的功能吗？ 谢谢

### ISSUE THREAD

**Issue by TeeangeHWei** [liangliangyy/DjangoBlog#295]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [x ] 请求技术支持

**Comment by guocdfeifei** [comment]
这个功能有了么？
