### ISSUE TITLE
CSRF验证失败 403 

### ISSUE THREAD

**Issue by cfstyle** [liangliangyy/DjangoBlog#307]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

![image](https://user-images.githubusercontent.com/3371512/62834326-073ec980-bc7d-11e9-8bb5-3a9905be094b.png)
登录页和admin的登录页都无法登录，报CSRF验证失败 403 日志如截图所示

**Comment by liangliangyy** [comment]
你好，可否提供下是如何复现的？

**Comment by changjiong** [comment]
请问下这个问题最后怎么解决的
