### ISSUE TITLE
留下网址

### ISSUE THREAD

**Issue by renchong73** [liangliangyy/DjangoBlog#308]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

感谢作者的开源项目，我用的uwsgi+nginx 网址为：wruixue.cn
再次感谢~

**Comment by liangliangyy** [comment]
感谢回复，我加到了 #214 中。这个issue我关了。

**Comment by liangliangyy** [comment]
感谢回复，我加到了 #214 中，这个issue我关了。
