### ISSUE TITLE
静态文件

### ISSUE THREAD

**Issue by javanan** [liangliangyy/DjangoBlog#309]
新建文章会生成静态文件吗？ 我直接拿静态文件放到 阿里云oss 之类的 是否也可以使用？

**Comment by liangliangyy** [comment]
你好，新建文章不会生成静态文件，你说的静态文件是图片之类的吧，放阿里云oss之类是可以的，但是需注意是否允许外链。

**Comment by javanan** [comment]
> 你好，新建文章不会生成静态文件，你说的静态文件是图片之类的吧，放阿里云oss之类是可以的，但是需注意是否允许外链。

嗯，不是图片或者css/js的意思。

我是想把文章内容直接生成html文件。这样可以部署在非web容器的服务器里，比如OSS或者CDN

**Comment by liangliangyy** [comment]
你说的是静态化吧，这个是不支持的。

**Comment by javanan** [comment]
可以商用吗？

**Comment by liangliangyy** [comment]
你好，我是使用MIT许可的，可以商用。不过请遵从MIT许可的要求。
