### ISSUE TITLE
您好，我配置了微博OAuth2.0, 错误码：21322 重定向地址不匹配

### ISSUE THREAD

**Issue by lihao0214** [liangliangyy/DjangoBlog#311]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持
我看了关闭的答案，http://www.sunxumin.com/article/2019/8/23/18.html 这是我碰到的问题，忘不吝赐教。谢谢

**Comment by liangliangyy** [comment]
你好，我刚刚试了下，是可以的呀。
