### ISSUE TITLE
后台上传图片，地址错误

### ISSUE THREAD

**Issue by johnson329** [liangliangyy/DjangoBlog#320]
后台上传图片，地址是media，urls设置在非调试模式下面不处理图片。nginx没配置，这算bug了吧

**Comment by johnson329** [comment]
location /media {
        # 静态文件配置
        alias /home/server/python/DjangoBlog/uploads/;
     }
拿走，估计作者没有图片，代码还是不能高亮。。。关闭我吧

**Comment by johnson329** [comment]
重启居然又能高亮了。。。

**Comment by johnson329** [comment]
作者呀，这代码字体太小了，你可以改一改伐

**Comment by liangliangyy** [comment]
感谢提醒，文章已经更新，字体小的话你改下css就可以了。
