### ISSUE TITLE
windows Django本地开发服务器 本地访问网页 很慢是什么问题？

### ISSUE THREAD

**Issue by weixiami** [liangliangyy/DjangoBlog#325]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ x] 请求技术支持

**Comment by hustcsxg** [comment]
F12看下估计是部分js库加载比较耗时
