### ISSUE TITLE
djangoblog.log和werobot_session文件无法使用相对路径Permission denied

### ISSUE THREAD

**Issue by jackylinwh** [liangliangyy/DjangoBlog#328]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x ] 请求技术支持

我使用Apache作为服务器,配置完成后出现两处错误,分别是:
```
'log_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'djangoblog.log',
            'maxBytes': 16777216,  # 16 MB
            'formatter': 'verbose'
        }
```
```
robot.config['SESSION_STORAGE'] = FileStorage(filename='werobot_session')
```
两个地方都提示文件无访问权限(permission denied),
后来把这两个文件名改成绝对路径就能正常工作了
这是否是BUG,又或者我需要额外的一些配置才能避免这两个问题?如有空闲,烦请告知,谢谢.

**Comment by liangliangyy** [comment]
执行代码的用户对当前代码目录没有写权限。

**Comment by jackylinwh** [comment]
> 执行代码的用户对当前代码目录没有写权限。

执行代码用户是www,用户组是www
代码放在 /home/www/htdocs/DjangoBlog下
www目录的权限如下：
`drwxr-x--- 4 www   www   4096 Oct 17 16:07 www`
而且它的子目录也都是这样子的
就是说执行代码的用户对整个项目所在的目录是有写权限的，但还是提示 permission denied错误
只有把`'filename': 'djangoblog.log',`改成
`'filename': os.path.join(BASE_DIR, 'djangoblog.log'),`才不会提示错误
