### ISSUE TITLE
关于部署后仍然是Welcome to nginx!页面的技术支持请求

### ISSUE THREAD

**Issue by IMSUVEN** [liangliangyy/DjangoBlog#330]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

按照https://www.lylinux.net/article/2019/8/5/58.html 的流程进行部署以后
访问页面仍然是Welcome to nginx!的页面

**Comment by liangliangyy** [comment]
要在sites-enabled目录删除默认的default配置文件，然后重启nginx就可以了。

**Comment by IMSUVEN** [comment]
> 要在sites-enabled目录删除默认的default配置文件，然后重启nginx就可以了。

感谢，已解决
