### ISSUE TITLE
markdown公式显示不正常

### ISSUE THREAD

**Issue by HDU38** [liangliangyy/DjangoBlog#331]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

![image](https://user-images.githubusercontent.com/37890618/67572057-02f85780-f768-11e9-878d-8b19fb751407.png) 
后台显示正常

![image](https://user-images.githubusercontent.com/37890618/67572111-20c5bc80-f768-11e9-90cf-278977f19752.png)
前端显示异常

**Comment by liangliangyy** [comment]
抱歉，最近有点忙没有看issue，好像是不支持公式，后台是js渲染的，前端是markdown解析器生成html的，我晚点看看有没有解决方案。

**Comment by SimonYYB** [comment]
请问找到这个问题的解决方案了吗
