### ISSUE TITLE
博主,此项目能否添加docker部署支持

### ISSUE THREAD

**Issue by lpdswing** [liangliangyy/DjangoBlog#333]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by liangliangyy** [comment]
你好，支持docker部署的，我自己现在的部署就是基于docker。

**Comment by lpdswing** [comment]
能否参考一下dockerfile，不知道创建超级用户的命令在里面是怎么体现的发自我的华为手机-------- 原始邮件 --------发件人： 且听风吟 <notifications@github.com>日期： 2019年11月1日周五 上午10:17收件人： liangliangyy/DjangoBlog <DjangoBlog@noreply.github.com>抄送： lpdswing <lpdswing@qq.com>, Author <author@noreply.github.com>主    题： Re: [liangliangyy/DjangoBlog] 博主,此项目能否添加docker部署支持 (#333)你好，支持docker部署的，我自己现在的部署就是基于docker。

**Comment by liangliangyy** [comment]
创建超级用户在第一次启动之后使用`docker exec` 命令就可以了，毕竟只创建一次就行了，没必要添加到dockerfile里面。

**Comment by lpdswing** [comment]
好像没有启动成功发自我的华为手机-------- 原始邮件 --------发件人： 且听风吟 <notifications@github.com>日期： 2019年11月1日周五 傍晚5:02收件人： liangliangyy/DjangoBlog <DjangoBlog@noreply.github.com>抄送： lpdswing <lpdswing@qq.com>, Author <author@noreply.github.com>主    题： Re: [liangliangyy/DjangoBlog] 博主,此项目能否添加docker部署支持 (#333)创建超级用户在第一次启动之后使用docker exec 命令就可以了，毕竟只创建一次就行了，没必要添加到dockerfile里面。

**Comment by kentio** [comment]
@lpdswing 使用Docker部署请移步[快速部署DjangoBlog](https://github.com/kentio/ondjblog) , 记得给个 `star` or `fork`
