### ISSUE TITLE
你好，小白一个，前来学习一下

### ISSUE THREAD

**Issue by pukun666** [liangliangyy/DjangoBlog#336]
Running setup.py install for rcssmin ... error
    Complete output from command e:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\pk\\AppData\\Local\\Temp\\pip-install-uhc8voey\\rcssmin\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\pk\AppData\Local\Temp\pip-record-ngu7_ua5\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying .\rcssmin.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_rcssmin' extension
    error: [WinError 3] 系统找不到指定的路径。: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'

    ----------------------------------------
Command "e:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\pk\\AppData\\Local\\Temp\\pip-install-uhc8voey\\rcssmin\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\pk\AppData\Local\Temp\pip-record-ngu7_ua5\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\pk\AppData\Local\Temp\pip-install-uhc8voey\rcssmin\

我这边执行执行pip的时候报错，不懂，希望大佬能指点一下

**Comment by liangliangyy** [comment]
请参考 #337
