### ISSUE TITLE
底部备案号网址错误

### ISSUE THREAD

**Issue by Shimon-Guo** [liangliangyy/DjangoBlog#341]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [x] 添加新的特性或者功能
- [x] 请求技术支持

底部备案号网址错误, 网址应该为http://www.beian.miit.gov.cn/，建议可以在后台直接修改网址。

**Comment by liangliangyy** [comment]
感谢提醒，已修改。
这个应该是当时手误写错了，这种网址一般都是固定的，没必要做成后台配置。
