### ISSUE TITLE
编辑文章添加图片点击上传图片出现错误

### ISSUE THREAD

**Issue by Mickls** [liangliangyy/DjangoBlog#343]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

我通过后台文章编辑器的图片点击上传功能上传我的图片，在后台里可以看到我点击的图片已经成功上传，但是图片地址并没有显示
![image](https://user-images.githubusercontent.com/41884581/71438235-d93fba80-272f-11ea-85ce-0c23f40afda3.png)
我查看console显示的是
![image](https://user-images.githubusercontent.com/41884581/71438261-f2e10200-272f-11ea-8728-b72f0d94427b.png)
我不太懂js，没办法排查问题到底出在哪，希望作者能够帮我看看到底发生了什么，我现在没办法发布我的文章了

**Comment by liangliangyy** [comment]
你好,我这里是正常的,请确认你的配置是否正确

**Comment by Mickls** [comment]
感谢作者的回复
我已经解决了我的问题，我发现是chrome浏览器的迅雷插件导致的问题，它让每一个页面都加上了一段多余的Element，js获取路径的时候因为多了一个结构导致解析出错。
