### ISSUE TITLE
新用户权限勾选`人员状态`后，该用户无法登录管理后台

### ISSUE THREAD

**Issue by spaceack** [liangliangyy/DjangoBlog#346]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

---

问题描述：

新增用户的权限
人员状态，指明用户是否可以登录到这个管理站点。即 is_staff字段勾选后，该用户并不能登录
[Django管理后台](http://127.0.0.1:8000/admin/login/?next=/admin/)，

提示错误“您当前以XXX登录，但是没有这个页面的访问权限。您想使用另外一个账号登录吗？ ”。 

必须要把超级管理选中才行。 

我希望在权限勾选`人员状态`后，该用户可以登录管理后台。

**Comment by liangliangyy** [comment]
是需要超级管理员才可以登录的.

**Comment by liangliangyy** [comment]
可以修改 
https://github.com/liangliangyy/DjangoBlog/blob/master/DjangoBlog/admin_site.py#L37
`is_superuser`为`is_staff`即可

**Comment by wangyangang** [comment]
> 可以修改
> https://github.com/liangliangyy/DjangoBlog/blob/master/DjangoBlog/admin_site.py#L37
> `is_superuser`为`is_staff`即可

亲测可用！
