### ISSUE TITLE
设置Google第三方登录的时候，会超时拒绝服务

### ISSUE THREAD

**Issue by Woooosz** [liangliangyy/DjangoBlog#35]
能够接入谷歌登录页，但是正确地输入用户名和密码之后，会提示502错误

查看错误记录如下：
`2017/09/29 17:32:50 [error] 4856#0: *709 upstream prematurely closed connection while reading response header from upstream, client:*******, server: ****, request: "GET /oauth/authorize?type=google&code=4/AVmFMJ9ygdGlQ9-zjpqpgyUyxgikK40k3-a_FYBK6r0&authuser=0&session_state=6185c4aec981246a737be03fb6f98514f6513923..a802&prompt=consent HTTP/1.1", upstream: "http://unix:/home/wwwroot/newBlog/DjangoBlog/run/gunicorn.sock:/oauth/authorize?type=google&code=4/AVmFMJ9ygdGlQ9-zjpqpgyUyxgikK40k3-a_FYBK6r0&authuser=0&session_state=6185c4aec981246a737be03fb6f98514f6513923..a802&prompt=consent", host: "*******"`

微博、github没有问题。

最后感谢您的项目，致敬

**Comment by liangliangyy** [comment]
请确定你的网络可以fq连接到Google的服务器.

**Comment by liangliangyy** [comment]
抱歉,刚刚没看清除你的描述.代码运行的网络环境和你登录Google的网络环境是同样的吗.如果是同样的网络的话请贴下更详细点的错误信息.

**Comment by Woooosz** [comment]
感谢回复，应该是我的vps无法访问谷歌，我查看了错误记录，也是由于超时所以抛出502错误的
有股醍醐灌顶的感觉，谢谢！！！！

**Comment by liangliangyy** [comment]
ok 这个issue我关掉了~~
