### ISSUE TITLE
运行./gunicorn_start.sh    connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by jibanli** [liangliangyy/DjangoBlog#353]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

![错误3](https://user-images.githubusercontent.com/39478794/74103658-e9e5ac00-4b88-11ea-8bf7-f02b4656a00b.png)
![错误2](https://user-images.githubusercontent.com/39478794/74103660-ec480600-4b88-11ea-9918-34da174664bf.png)
![错误1](https://user-images.githubusercontent.com/39478794/74103661-ed793300-4b88-11ea-9091-26025984c3f9.png)

**Comment by jibanli** [comment]
结果，http://域名  显示
![结果1](https://user-images.githubusercontent.com/39478794/74103703-4ba61600-4b89-11ea-9429-aaffae3927b3.png)

**Comment by jibanli** [comment]
本人小白，请博主指点

**Comment by xxsgit** [comment]
我也是出现这样的问题，应该是调用static库出现了问题，另外

> **我确定我已经查看了** (标注`[ ]`为`[x]`)
> 
> * [x]  [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
> * [x]  [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
> * [x]  [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)
> 
> **我要申请** (标注`[ ]`为`[x]`)
> 
> * [ ]  BUG 反馈
> * [ ]  添加新的特性或者功能
> * [x]  请求技术支持
> 
> ![错误3](https://user-images.githubusercontent.com/39478794/74103658-e9e5ac00-4b88-11ea-8bf7-f02b4656a00b.png)
> ![错误2](https://user-images.githubusercontent.com/39478794/74103660-ec480600-4b88-11ea-9918-34da174664bf.png)
> ![错误1](https://user-images.githubusercontent.com/39478794/74103661-ed793300-4b88-11ea-9091-26025984c3f9.png)

8000端口已经被占用，解决方法可以看https://blog.csdn.net/weixin_42547786/article/details/97933466

**Comment by xxsgit** [comment]
兄弟，排版问题我觉得是由于版主更新了css stytle造成的，可以下载前面版本的源代码解决。
