### ISSUE TITLE
django2.2和mysql兼容性问题

### ISSUE THREAD

**Issue by pptfz** [liangliangyy/DjangoBlog#356]
centos7.5+python3.6.9+virtualenv同步数据库报错兼容性问题如下
python3 ./manage.py makemigrations
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 0.9.3.

尝试多种方法，无法解决
尝试方法：https://blog.csdn.net/lpw_cn/article/details/103978909
https://blog.csdn.net/weixin_45476498/article/details/100098297

**Comment by jifferent** [comment]
你的mysqlclient的版本太低， 尝试过升级mysqlclient吗？
