### ISSUE TITLE
搭建失败

### ISSUE THREAD

**Issue by GuiXieKJ** [liangliangyy/DjangoBlog#357]
我的页面无法正常解析js和css
![截屏2020-02-20上午9 50 26](https://user-images.githubusercontent.com/49875020/74893107-7f254380-53c6-11ea-9de1-4e8ceaf098cd.png)
怎么解决？

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [] BUG 反馈
- [] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by xbk2000** [comment]
没有人是相同的问题吗，我也是这个问题，界面加载不出css和js，显示403错误，弄了好久了都没好

**Comment by fhrl94** [comment]
查了好久<djangoblog.com.conf>
```
    location /static/ {
        alias XXX
        expires max;
        access_log        off;
        log_not_found     off;
    }
```
改为, 少一个 /
```
    location /static {
        alias XXX
        expires max;
        access_log        off;
        log_not_found     off;
    }
```

**Comment by fhrl94** [comment]
还有一个可能是 nginx 要root权限, 关键词 django 403 静态文件

**Comment by xbk2000** [comment]
我已经部署成功了,是因为权限的原因,之前我以root用户的权限运行,无法加载.之后另外创建一个用户运行,就加载成功了

**Comment by qq923004243** [comment]
哇 我还是没有成功 也是样式没有成功 装了 2天 不下20次。。。

**Comment by RooterN** [comment]
DoesNotExist at /admin/blog/article/add/
Site matching query does not exist.
我搭建好后，其他都没问题，但是新增文章开启debug，总是报这个错误，是哪里有问题呢？
