### ISSUE TITLE
请教网站的配置，如SITE_NAME 等是如何传递给Template的？

### ISSUE THREAD

**Issue by wangyangang** [liangliangyy/DjangoBlog#358]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

---

你好，我在看你的源码的时候，有个问题一直搞不明白：
后台admin管理界面，blog app里的BlogSettings里的网站名称、网站描述等信息，
是如何给到Django模板使用的？我看了一下，没找到任何View把这些信息传给Template啊。
例如：base.html 里的 {{ SITE_NAME }}  这个。
还是我看的不够仔细？请指教

**Comment by liangliangyy** [comment]
用的是context_processors,位置在  https://github.com/liangliangyy/DjangoBlog/blob/888a3ff5c53c220822ba50b32129dc1fc2da744a/blog/context_processors.py#L33
请参考官方文档: https://docs.djangoproject.com/en/3.0/topics/templates/
