### ISSUE TITLE
是否能添加支持HTML格式的功能?

### ISSUE THREAD

**Issue by VoldemortGin** [liangliangyy/DjangoBlog#363]
你好, 我的一些博客是用html写的, 想知道能否添加这个功能到这个项目里呢? 
补充: 一些深度学习的内容, 我想把Jupyter Notebook的计算过程放在里面, html能更好地支持这种效果. 谢谢.
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by liangliangyy** [comment]
抱歉,暂时markdown可以满足我的需求,另外markdown应该是支持写html进来的吧.

**Comment by VoldemortGin** [comment]
我尝试过粘贴html的, 富文本编辑器里预览只能看到源码.
