### ISSUE TITLE
考虑过把后台替换为xadmin吗? 

### ISSUE THREAD

**Issue by VoldemortGin** [liangliangyy/DjangoBlog#364]
大神你好, 考虑过把后台替换为xadmin吗? 目前的admin风格感觉太寡淡了, 也不支持许多xadmin里有的功能.

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by liangliangyy** [comment]
你好,暂时没有这样的考虑.现在的后台可以满足我的需求.
