### ISSUE TITLE
Windows安装requirement包编译错误

### ISSUE THREAD

**Issue by H2ydrogen** [liangliangyy/DjangoBlog#366]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

环境：python 3.8.2  django 3.0.2

问题描述：项目根目录下输入 pip install -Ur requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple 时，安装evernote包时出现编译错误

错误信息：
 ERROR: Command errored out with exit status 1:
     command: 'c:\users\h2ydrogen\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\H2ydrogen\\AppData\\Local\\Temp\\pip-install-ts73936p\\evernote\\setup.py'"'"'; __file__='"'"'C:\\Users\\H2ydrogen\\AppData\\Local\\Temp\\pip-install-ts73936p\\evernote\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\H2ydrogen\AppData\Local\Temp\pip-install-ts73936p\evernote\pip-egg-info'
         cwd: C:\Users\H2ydrogen\AppData\Local\Temp\pip-install-ts73936p\evernote\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\H2ydrogen\AppData\Local\Temp\pip-install-ts73936p\evernote\setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
![A`LVPAC63KILY_@HBSM4R88](https://user-images.githubusercontent.com/52595996/75549640-16dffd00-5a6b-11ea-8472-ba40a87880ca.png)

我查了evernote官方文档（Pypi），上面说这个包只支持python2.x，对python3.x只有测试版，我下载了这个包，并且通过set.py 安装，重试pip install -Ur requirements.txt，依然报错同样内容。

第一次发帖，如有疏漏和不周，敬请谅解

**Comment by liangliangyy** [comment]
抱歉,我使用`pip freeze | grep evernote` 命令没有看到有依赖evernote 这个包.
