### ISSUE TITLE
关于简单的SEO功能

### ISSUE THREAD

**Issue by ralph0813** [liangliangyy/DjangoBlog#370]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

关于:  简单的SEO功能，新建文章等会自动通知Google和百度。

1、如何判断是否成功通知百度和Google？直接去搜索行发布的内容无法搜索到。
2、如果只是更新内容并保存，会通知百度或者谷歌吗？

**Comment by stackia** [comment]
1. 百度SEO主动推送，需要在 [settings.py](https://github.com/liangliangyy/DjangoBlog/blob/master/DjangoBlog/settings.py#L197) 配置好自己的主动推送接口。接口申请地址：https://ziyuan.baidu.com/linksubmit/index
2. 百度搜索资源平台后台能看到主动推送统计
![image](https://user-images.githubusercontent.com/5107241/77162663-6ef8a500-6ae7-11ea-9713-cde25dfe55ea.png)
3. google 推送无法得知是否成功，不过如果你的服务器架在国内，大概率是失败的。因为底层调用的是 https://www.google.com/webmasters/tools/ping 接口，这个 API 墙内是不通的
4. 无论是百度还是Google，SEO推送后并不代表会出现在搜索结果里，只是告知百度Google“我这里有个网站，快来爬呀”，然而搜索引擎爬虫大概率不会收录没有权重的新站

**Comment by ralph0813** [comment]
感谢，设置好之后测试了一下，百度云服务器，谷歌能正常推送，能正常搜索到，反倒是百度搜索不到。
