### ISSUE TITLE
管理站点添加文章时显示“哎呀，出错了，我已经收集到了错误信息，之后会抓紧抢修，请点击首页看看别的？”

### ISSUE THREAD

**Issue by xbk2000** [liangliangyy/DjangoBlog#371]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x ] 请求技术支持

**Comment by naiyouweibaomihua** [comment]
看看是不是站点管理的example.com没有修改
