### ISSUE TITLE
请求合并被拦截了

### ISSUE THREAD

**Issue by Chise1** [liangliangyy/DjangoBlog#379]
我申请的使用simpleui美化django-admin后台管理系统无法合并成功。

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ x] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by liangliangyy** [comment]
非常感谢你的提交，但是因为自带的admin后台完全够用，所以我不太希望引入第三方组件来增加系统的不稳定性和复杂性，因此该pr  #380  不能被合并。
