### ISSUE TITLE
后台图片上传设置

### ISSUE THREAD

**Issue by FurtherGazer** [liangliangyy/DjangoBlog#386]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

Hi，在进行 admin 后台文章编辑，进行图片上传时发现会出现类似如下报错：
```
Uncaught DOMException: Blocked a frame with origin "http://127.0.0.1:8001" from accessing a cross-origin frame.
    at HTMLIFrameElement.uploadIframe.onload 
```

经查验，可能是由于 settings.py 中没有添加 X_FRAME_OPTIONS = 'SAMEORIGIN'  

根据 https://github.com/pylixm/django-mdeditor 官方文档说明，对于 Django 3.0+，可能需要进行该设置，否则会影响图片的上传。

**Comment by liangliangyy** [comment]
感谢提醒.
