### ISSUE TITLE
你的博客qq oauth登录貌似有bug

### ISSUE THREAD

**Issue by supersu097** [liangliangyy/DjangoBlog#389]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持
你的博客qq oauth登录貌似有bug，手机上确认完跳转之后还要用户名和密码

**Comment by liangliangyy** [comment]
感谢反馈.我刚刚试了下是正常的.还麻烦详细描述下复现过程.

**Comment by supersu097** [comment]
> 感谢反馈.我刚刚试了下是正常的.还麻烦详细描述下复现过程.

那可能是偶发性bug吧，比较难排障。至于复现嘛，我就是正常流程用qq扫码登录然后就发现登录不了，本来扫完码该跳到文章详情页的但却跳到了登录页，另外扫完码在手q上确认之后，手q一直在转圈圈，过了几十秒pc端页面才有反应，不知道是不是网络问题，我在这个博客https://www.88cto.com/用手q扫码登录一切正常，你可以试试，这个网站也是基于django的

**Comment by liangliangyy** [comment]
感谢反馈.我成功复现了.稍后修复.

**Comment by supersu097** [comment]
> 感谢反馈.我成功复现了.稍后修复.

修复完了告诉我一下哈，我测试测试~
