### ISSUE TITLE
有没有计划新增微信Oauth登录呀~

### ISSUE THREAD

**Issue by supersu097** [liangliangyy/DjangoBlog#390]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ x] 添加新的特性或者功能
- [ ] 请求技术支持

毕竟qq用的越来越少了，微博也有很多人不玩了~

**Comment by stackia** [comment]
微信登录 需要有认证过的服务号才能做，门槛过高，就算加入了支持，我相信也没多少人能用起来😂

**Comment by supersu097** [comment]
> 微信登录 需要有认证过的服务号才能做，门槛过高，就算加入了支持，我相信也没多少人能用起来😂

哦哦，长知识了~
