### ISSUE TITLE
您好，runserver之后可以访问就是首页只有文字没有图片显示

### ISSUE THREAD

**Issue by lemonYZ** [liangliangyy/DjangoBlog#393]
**我确定我已经查看了** (标注`[ []`为`[x]`)]

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [x] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by lemonYZ** [comment]
http://127.0.0.1:8000/路由可以正常访问  只是没有图片显示，检查了static那块的内容没有问题 还是未能解决，打扰您能不能帮我解决这个问题，谢谢啦

**Comment by liangliangyy** [comment]
你看看是不是debug设置成了true。
debug=true的话django是不会host静态文件，需要使用nginx等。

**Comment by lemonYZ** [comment]
got it ，谢谢 我去试试

**Comment by lemonYZ** [comment]
> 你看看是不是debug设置成了true。
> debug=true的话django是不会host静态文件，需要使用nginx等。

got it  谢谢，我去试试

**Comment by lemonYZ** [comment]
got it ！ 谢谢 我去试试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"且听风吟"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月4日(星期六) 晚上6:34
收件人:&nbsp;"liangliangyy/DjangoBlog"<DjangoBlog@noreply.github.com&gt;;
抄送:&nbsp;"杨航"<752611671@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liangliangyy/DjangoBlog] 您好，runserver之后可以访问就是首页只有文字没有图片显示 (#393)





 
你看看是不是debug设置成了true。
 debug=true的话django是不会host静态文件，需要使用nginx等。
