### ISSUE TITLE
建议后台去掉网站统计代码 必填字段。

### ISSUE THREAD

**Issue by xjzyy** [liangliangyy/DjangoBlog#400]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by xjzyy** [comment]
从子目录跳转父目录提示页面不存在。

**Comment by yhyPython110** [comment]
为啥新增文章---选择作者那一栏 一直没有选择值 文章创建一直失败

**Comment by xjzyy** [comment]
作者你好，文章和评论的，markdown并没有生效，是不是集成的有bug？
