### ISSUE TITLE
网站迁移之后出现了搜索功能不能用，原先能搜索到的关键字，现在都提示找不到。

### ISSUE THREAD

**Issue by ading2016** [liangliangyy/DjangoBlog#401]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by liangliangyy** [comment]
尝试重建下索引，执行：
`python manage.py rebuild_index`
