### ISSUE TITLE
请问是否可以再添加一个找回密码功能

### ISSUE THREAD

**Issue by Super-Gil** [liangliangyy/DjangoBlog#404]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x ] 添加新的特性或者功能
- [ ] 请求技术支持

请问是否可以再添加一个找回密码功能
我学习了您写的关于注册登陆的功能，请问是否缺少了一个找回密码的功能 我似乎并没有找到 如果您能稍微花点时间写一下那部分的代码 我将感激不尽

**Comment by liangliangyy** [comment]
你好，感谢你的反馈，我最近事情比较多，没太多时间来维护。
如果觉得有什么功能缺失的话，欢迎提交pr来完善。

**Comment by wanzhonggang** [comment]
添加这个功能前端代码加一点   后端接受处理一下就好了 
可以邮件找回  也可以电话找回  主要看作者绑定的是什么了
