### ISSUE TITLE
请问下您这个 cache 处理是在哪儿系统学的

### ISSUE THREAD

**Issue by actble** [liangliangyy/DjangoBlog#41]
### 我把官网上的redis cache 弄过， 但是你这个md5， cache 我完全摸不到边

**Comment by liangliangyy** [comment]
你说的是md5缓存key的吗?其实就是把方法名和参数等做md5,以免缓存key过长而已.
然后cache_decorator是使用的装饰器而已.

**Comment by actble** [comment]
嗯， 谢谢，我今天看了下代码； 没有设计网络回路里面深层的东西， 都看懂了。
