### ISSUE TITLE
RSS订阅信息里文章地址没有携带端口

### ISSUE THREAD

**Issue by hongweipeng** [liangliangyy/DjangoBlog#410]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [x] 添加新的特性或者功能

![20200610113001](https://user-images.githubusercontent.com/7546325/84223917-c9653880-ab0d-11ea-99ae-e960db21a0d0.png)

**Comment by liangliangyy** [comment]
请查看你的site配置，是否有携带端口号。
