### ISSUE TITLE
ubuntu 20.04出错 selecting 'python-dev-is-python2' instead of 'python-dev'

### ISSUE THREAD

**Issue by winner106** [liangliangyy/DjangoBlog#420]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by doubuhao** [comment]
此处由于python3中已删除python-dev-is-python2而django中未删除，可以直接pip six,在把six.py复制到python/lib/site-packages\django\utils文件夹下，然后更改python/lib/site-packages\django\utils\encoding.py文件，在里面添加如下代码

import six
def python_2_unicode_compatible(klass):
	return six.python_2_unicode_compatible(klass)

可以解决您的问题。

如果遇到Error loading MySQLdb module: No module named 'MySQLdb'的错误，原因是python3改变了连接库，不再使用MySQLdb来连接数据库，而使用pymysql库来连接数据库。可以在此项目DjangoBlog文件夹中__init__.py里添加如下代码：
import pymysqlpymysql.install_as_MySQLdb()
当然，在这之前您应该先pip按照pymysql模块。

**Comment by doubuhao** [comment]
> selecting 'python-dev-is-python2' instead of 'python-dev' ubuntu 20.04出错

此处由于python3中已删除python-dev-is-python2而django中未删除，可以直接pip six,在把six.py复制到python/lib/site-packages\django\utils文件夹下，然后更改python/lib/site-packages\django\utils\encoding.py文件，在里面添加如下代码

import six
def python_2_unicode_compatible(klass):
return six.python_2_unicode_compatible(klass)

可以解决您的问题。

如果遇到Error loading MySQLdb module: No module named 'MySQLdb'的错误，原因是python3改变了连接库，不再使用MySQLdb来连接数据库，而使用pymysql库来连接数据库。可以在此项目DjangoBlog文件夹中__init__.py里添加如下代码：
import pymysqlpymysql.install_as_MySQLdb()
当然，在这之前您应该先pip按照pymysql模块。
