### ISSUE TITLE
ubuntu nginx 部署后 502 Bad Gateway ,Gunicorn 能跑通，就是nginx出错，导致后面supervisor也出错，都是按照您的配置来的，希望您能指点一下

### ISSUE THREAD

**Issue by internet96** [liangliangyy/DjangoBlog#423]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by liangliangyy** [comment]
请贴一下详细的报错信息吧。

**Comment by internet96** [comment]
(env) root@iZuf67bo9s80z9i5es8kbxZ:~/Python-3.7.0# cd ..
(env) root@iZuf67bo9s80z9i5es8kbxZ:~# python3
Python 3.7.0 (default, Sep 20 2020, 23:12:27) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'



这是一个新的问题，ubuntu14 python3.7找不到 _ssl, 我按照网上博客的方式 改了setup.dist 里的内容 重新编译 还是 报这个错，求指导。

**Comment by yanhuixie** [comment]
> 这是一个新的问题，ubuntu14 python3.7找不到 _ssl, 我按照网上博客的方式 改了setup.dist 里的内容 重新编译 还是 报这个错，求指导。

你的python3.7是怎样安装的？

**Comment by miserableworld** [comment]
python3.7安装有问题，没指定openssl，建议你重新安装下python3

**Comment by w5dy** [comment]
我出现和楼主标题一样的问题,怎么解决的呀,重新安装了python3?但是为什么Gunicorn没有问题,可以跑通
