### ISSUE TITLE
你好 请问docker版本和宿主机是什么版本，搞了好久一直报错

### ISSUE THREAD

**Issue by zlaiyyf** [liangliangyy/DjangoBlog#424]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by liangliangyy** [comment]
请参考这篇文章，有详细的部署介绍
https://www.lylinux.net/article/2019/8/5/58.html

**Comment by zlaiyyf** [comment]
谢谢我已经部署好了，请您看一下我的pull requests，这是我遇到docker遇到的问题和解决办法

**Comment by zlaiyyf** [comment]
我 修改了pull requests
