### ISSUE TITLE
文章添加功能无法使用（后台->blog->文章->添加）

### ISSUE THREAD

**Issue by 12qwertyuiop** [liangliangyy/DjangoBlog#427]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持
作者你好

我在控制台查看发现get请求放回500状态码。别的添加侧边栏都可以使用，就添加文章返回500然后跳到主页了。想知道该怎么解决。

**Comment by naiyouweibaomihua** [comment]
看看是不是站点管理没有修改
