### ISSUE TITLE
fork的分支actions报错

### ISSUE THREAD

**Issue by Chise1** [liangliangyy/DjangoBlog#431]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

我fork了你的最新分支，增加了docker和docker-compose的文件，初始化了poetry的包管理器。但是还没有修改任何逻辑代码，然后我发现你配置的actions就报错，内容如下：

ERROR: test_own_track_log (owntracks.tests.OwnTrackLogTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/DjangoBlog/DjangoBlog/owntracks/tests.py", line 55, in test_own_track_log
    convert_to_amap([s])
  File "/home/runner/work/DjangoBlog/DjangoBlog/owntracks/views.py", line 88, in convert_to_amap
    convert_result.append(result['locations'])
KeyError: 'locations'
我看了对应的位置，不太清楚为什么会报这个问题，你是怎么过的。

**Comment by liangliangyy** [comment]
现在是会有这个错误，是因为高德地图的api被删了。
