### ISSUE TITLE
ZeroDivisionError-float division by zero

### ISSUE THREAD

**Issue by shendy1991** [liangliangyy/DjangoBlog#44]
![ea3bf531-3430-4b1f-aaed-f277b86167e2](https://user-images.githubusercontent.com/14012553/32552221-2f160e12-c4ce-11e7-8e06-c15573c6d572.png)

这段代码。后台加了tag之后，就会运行报错。

count 会等于0，以至于dd也等于0 然后报错
不知道博主遇到没。

**Comment by liangliangyy** [comment]
可以贴下详细的错误堆栈吗?好像是除0报错的.

**Comment by shendy1991** [comment]
对的。就是除0的报错。

**Comment by liangliangyy** [comment]
所以是len(tags)=0导致的吗?但是如果长度是0的话是不会进到这里的吧.

**Comment by shendy1991** [comment]
不。是有tag的。反正我加了几个tag之后。就crash了。如果不加tag。反而不会crash。难道你那边不能复现么？

**Comment by liangliangyy** [comment]
没有复现，我先暂时再加下长度判断，你那里如果还crash的话麻烦把详细的错误信息还有数据库中的`Tag`表的数据贴一下。
