### ISSUE TITLE
Error OnlineMiddleware: This FileResponse instance has no `content` attribute.

### ISSUE THREAD

**Issue by hongweipeng** [liangliangyy/DjangoBlog#440]
![image](https://user-images.githubusercontent.com/7546325/105567019-5772f400-5d6a-11eb-8328-60287416fc29.png)

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by sundyloveme** [comment]
你做了什么事情，触犯了这错误？
