### ISSUE TITLE
django交流

### ISSUE THREAD

**Issue by Speditor** [liangliangyy/DjangoBlog#441]
你好楼主，请问你有QQ交流群 或者微信群吗  想和你请教一下你的工程项目

**Comment by liangliangyy** [comment]
你好，没有交流群，有什么问题可以邮件我，有时间的话我会尽快回复你的。

**Comment by noodv** [comment]
我一直在用你这套模板，面面很多我自己改进了，有些功能想要，能找你有空加加吗？有偿
