### ISSUE TITLE
不能load静态文件

### ISSUE THREAD

**Issue by zhangjiashen** [liangliangyy/DjangoBlog#444]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

按照https://www.lylinux.net/article/2019/8/5/58.html 部署之后不能加载静态文件, 截了张首页的图，求指导!
![image](https://user-images.githubusercontent.com/15145699/108584852-63b28880-72f9-11eb-9009-32442a2d3dfd.png)

**Comment by liangliangyy** [comment]
这个是没权限，请不要使用root用户部署，或者修改静态资源的权限。
