### ISSUE TITLE
普通用户不能发博客啊？？

### ISSUE THREAD

**Issue by qwganker** [liangliangyy/DjangoBlog#445]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by liangliangyy** [comment]
你好，不可以，只有超级用户可以。
