### ISSUE TITLE
新增文章页面提交后出错

### ISSUE THREAD

**Issue by jindaxiang** [liangliangyy/DjangoBlog#447]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

```
Internal Server Error: /admin/blog/article/add/

ConnectionError at /admin/blog/article/add/
ConnectionError(<urllib3.connection.HTTPConnection object at 0x7ff64601caf0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7ff64601caf0>: Failed to establish a new connection: [Errno 111] Connection refused)
```

**Comment by SomnusYang** [comment]
怎么解决的兄弟
