### ISSUE TITLE
没问题，就是来赞👍一个

### ISSUE THREAD

**Issue by noodv** [liangliangyy/DjangoBlog#448]
确实是不错的项目，自已平时是用create-react-app, antdesign pro写前后端开发。

需要一个工程来做seo cms，来来回回看了好久，最终选定这套，真心不错.

前台页面有待优化，有空的话，我也开源一套python出来。基于你的。

**Comment by liangliangyy** [comment]
感谢支持，页面优化欢迎提交pr。
