### ISSUE TITLE
博客挂了

### ISSUE THREAD

**Issue by yexia553** [liangliangyy/DjangoBlog#457]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [X] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [X] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ X] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [X] 请求技术支持
https://www.lylinux.net/ 博客站点好像挂了一段时间了，请问是不再运行了吗？

**Comment by liangliangyy** [comment]
已经恢复了，感谢关注。
