### ISSUE TITLE
样式表链接无法域名结合

### ISSUE THREAD

**Issue by Jeck-Liu-Create** [liangliangyy/DjangoBlog#468]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持
 配置成功后 http://www.tcly.club/ 的前端CSS表链接无法自动和域名结合。

**Comment by liangliangyy** [comment]
你的网站没办法打开，另外问题也没怎么看明白，可以详细描述下吗？

**Comment by Jeck-Liu-Create** [comment]
这个问题已经找到了，出在nginx权限问题。
不过现在又遇到另一个问题supervisor 配置问题
`(djangoblog) root@iZ2zeffygi8nlfkhu02l4fZ:~# /usr/bin/python3 /usr/local/bin/supervisord -n -c  /etc/supervisor/supervisord.conf
2021-06-16 11:41:27,438 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-06-16 11:41:27,441 WARN For [program:djangoblog], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2021-06-16 11:41:27,441 INFO Included extra file "/etc/supervisor/conf.d/djangoblog.conf" during parsing
2021-06-16 11:41:27,452 INFO RPC interface 'supervisor' initialized
2021-06-16 11:41:27,452 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-06-16 11:41:27,452 INFO supervisord started with pid 9200
2021-06-16 11:41:28,455 INFO spawned: 'djangoblog' with pid 9212
2021-06-16 11:41:29,833 INFO success: djangoblog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
`
问题不知道出在那里。

**Comment by liangliangyy** [comment]
这个日志看起来貌似是启动了的呀

**Comment by Jeck-Liu-Create** [comment]
执行完这个命令后，一直返回，不停止。
`2021-06-17 09:38:20,055 INFO success: djangoblog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-06-17 09:38:20,055 INFO exited: djangoblog (exit status 127; not expected)
2021-06-17 09:38:21,057 INFO spawned: 'djangoblog' with pid 4703
`

**Comment by Jeck-Liu-Create** [comment]
重启后就没有了
`
root@iZ2zeffygi8nlfkhu02l4fZ:~# ps aux | grep supervisord 
root         994  0.0  0.0   9032   732 pts/0    S+   09:55   0:00 grep --color=auto supervisord

`

**Comment by Jeck-Liu-Create** [comment]
[部署为成功问题和配置文件内容.md](https://github.com/liangliangyy/DjangoBlog/files/6668634/default.md)

**Comment by Jeck-Liu-Create** [comment]
## 部署为成功问题和配置文件内容
> 未报错但是无法通过IP或域名访问；无需使用./manage.py runserver 开机可以通过 w3m http://127.0.0.1:8000 访问，nginx日至都为空猜测问题出在nginx；
> 以下是部分配置文件内容

> Djangoblog 工程在/root/python/下

> 我这里使用的域名是www.tcly.club

* ### 1、djangoblog.com.conf 
```
[program:djangoblog]
command = /root/python//gunicorn_start.sh
user = root
autostart=true
autorestart=true

redirect_stderr = true
stdout_logfile = /var/log/djangoblog.log
stderr_logfile=/var/log/djangoblog.err

```
* ### 2、supervisord.conf
 
 ```
 
 ; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf

 ```
 
 * ### 3、nginx配置文件
 ```
 server {

    listen 80;
    server_name www.tcly.club;
    root /root/python/DjangoBlog/;

    access_log /var/log/nginx/django_access.log;
    error_log /var/log/nginx/django_error.log;

    location /static/ {
        alias /root/python//DjangoBlog/collectedstatic/;
        expires max;
        access_log        off;
        log_not_found     off;
    }
    location /media {
        # 静态文件配置
        alias /root/python/DjangoBlog/uploads/;
        expires max;
    }
    location ~ \.py$ {
        return 403;
    }

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_redirect off;
        if (!-f $request_filename) {
            proxy_pass http://127.0.0.1:8000;
            break;
        }
    }

}

 
 ```
 
 * ### [djangoblog.log](https://note.youdao.com/s/GgJMglkE)
 * ### [supervisord.log](https://note.youdao.com/s/aN6aX7oY)

**Comment by Jeck-Liu-Create** [comment]
### 我开把自己蠢哭了
* 第一次使用阿里云之前一直使用的是搬瓦工，阿里云控制台要开启端口才行。

**Comment by liangliangyy** [comment]
对，阿里云要开端口的，部署的话可以参考 https://www.lylinux.net/article/2019/8/5/58.html  这个issue我就先close了。
