### ISSUE TITLE
The current path, blog/, didn’t match any of these.

### ISSUE THREAD

**Issue by kuyesu** [liangliangyy/DjangoBlog#470]
I get errors but try and failed , what could be the challenge for me, I will appreciate any help. I have been using the google translator to understand the documentation. please help me

Using the URLconf defined in DjangoBlog.urls, Django tried these URL patterns, in this order:

### ### ^admin/
[name='index']
page/<int:page>/ [name='index_page']
article/<int:year>/<int:month>/<int:day>/<int:article_id>.html [name='detailbyid']
category/<slug:category_name>.html [name='category_detail']
category/<slug:category_name>/<int:page>.html [name='category_detail_page']
author/<author_name>.html [name='author_detail']
author/<author_name>/<int:page>.html [name='author_detail_page']
tag/<slug:tag_name>.html [name='tag_detail']
tag/<slug:tag_name>/<int:page>.html [name='tag_detail_page']
archives.html [name='archives']
links.html [name='links']
upload [name='upload']
refresh [name='refresh']
mdeditor/
article/<int:article_id>/postcomment [name='postcomment']
^login/$ [name='login']
^register/$ [name='register']
^logout/$ [name='logout']
account/result.html [name='result']
oauth/authorize
oauth/requireemail/<int:oauthid>.html [name='require_email']
oauth/emailconfirm/<int:id>/<sign>.html [name='email_confirm']
oauth/bindsuccess/<int:oauthid>.html [name='bindsuccess']
oauth/oauthlogin [name='oauthlogin']
^sitemap\.xml$ [name='django.contrib.sitemaps.views.sitemap']
^feed/$
^rss/$
^search
robot
owntracks/logtracks [name='logtracks']
owntracks/show_maps [name='show_maps']
owntracks/get_datas [name='get_datas']
owntracks/show_dates [name='show_dates']
^static/(?P<path>.*)$
^media/(?P<path>.*)$

**Comment by liangliangyy** [comment]
Can you show your Nginx configuration?

**Comment by kuyesu** [comment]
i change the requirement.txt file where there was django-jet i replaced with django-3-jet and it worked out. thank you for consideration
