### ISSUE TITLE
能否加个开关，是否需要邮件验证激活新注册用户

### ISSUE THREAD

**Issue by mikolaje** [liangliangyy/DjangoBlog#477]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ x] 添加新的特性或者功能
- [ ] 请求技术支持

能否加个开关，是否需要邮件验证激活新注册用户。谢谢哈。

**Comment by liangliangyy** [comment]
这个功能建议自己实现下哈，因为不是主线功能。

**Comment by mikolaje** [comment]
> 这个功能建议自己实现下哈，因为不是主线功能。

好的，这个接受PR么，我看看哈。
