### ISSUE TITLE
后台的css找不到

### ISSUE THREAD

**Issue by zhangsj** [liangliangyy/DjangoBlog#49]
open() "/root/bbs/dblog/DjangoBlog/collectedstatic/admin/css/base.css" failed (2: No such file or directory)

[root@  DjangoBlog]# cd collectedstatic/
[root@  collectedstatic]# ls
CACHE
[root@  collectedstatic]# ls CACHE/
css  js
[root@  collectedstatic]# ls CACHE/css/
c0e3a556b93c.css  e3a8f975b83f.css  e7c1c03fad03.css
[root@  collectedstatic]#

**Comment by liangliangyy** [comment]
执行下 ./manage.py compress --force

**Comment by liangliangyy** [comment]
请参见readme
