### ISSUE TITLE
是否可以增加首页类别顺序的顺序指定功能

### ISSUE THREAD

**Issue by mikolaje** [liangliangyy/DjangoBlog#490]
![image](https://user-images.githubusercontent.com/11773334/126768688-291cdaf4-8ab1-4701-ac7d-637656662469.png)

如图所示。能否可以在管理平台里设定分类顺序。谢谢

**Comment by liangliangyy** [comment]
这个功能可以有，等后续有时间了加下。

**Comment by laozijiaojiangnan** [comment]
> 这个功能可以有，等后续有时间了加下。

这种排序方式可以吗
![image](https://user-images.githubusercontent.com/49054842/132838474-1763235e-9d79-4ce4-810d-18ae57637cce.png)

**Comment by laozijiaojiangnan** [comment]
如果可以的话，我就提个PR，0_0
