### ISSUE TITLE
docker部署Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/code/DjangoBlog/bin/docker_start.sh": permission denied: unknown.问题

### ISSUE THREAD

**Issue by Zhz4** [liangliangyy/DjangoBlog#495]
docker部署Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/code/DjangoBlog/bin/docker_start.sh": permission denied: unknown.问题

**Comment by liangliangyy** [comment]
是不是这个文件没有可执行权限？加下可执行权限再试试
