### ISSUE TITLE
是否增加[TOC]标签自动生成目录功能？

### ISSUE THREAD

**Issue by hermanzhaozzzz** [liangliangyy/DjangoBlog#509]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [x] 请求技术支持

你好，我想问一下，在后台编辑文章时，可以使用`[TOC]`标记，并在预览中看到目录，但是发表blog文章之后，在网页中显示[TOC]文本，而不能生成目录内容，请问有没有考虑实现目录功能呢，或者我miss掉了什么可以设置的东西？

**Comment by liangliangyy** [comment]
这个现在是不支持。

**Comment by hermanzhaozzzz** [comment]
谢谢，这个考虑增加嘛，还是一个蛮重要的功能的

——————————————————————
ZHAO Hua-nan

Ph. D. student
School of Life Sciences, Tsinghua University

Ph. D. Joint training
School of Life Sciences, Peking University



在 2021年9月24日 +0800 AM11:25，且听风吟 ***@***.***>，写道：

**Comment by liangliangyy** [comment]
这个在后续规划的功能里面的。

**Comment by hermanzhaozzzz** [comment]
好的！谢谢

——————————————————————
ZHAO Hua-nan

Ph. D. student
School of Life Sciences, Tsinghua University

Ph. D. Joint training
School of Life Sciences, Peking University



在 2021年9月24日 +0800 PM3:37，且听风吟 ***@***.***>，写道：
