### ISSUE TITLE
注册账号时收不到邮件，垃圾箱也没有，是不能用gamail么？

### ISSUE THREAD

**Issue by caixxiong** [liangliangyy/DjangoBlog#510]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by caixxiong** [comment]
qq邮箱也收不到邮件

**Comment by liangliangyy** [comment]
qq邮箱配置可以参考：
```
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST = 'smtp.exmail.qq.com'
EMAIL_PORT = 587
EMAIL_HOST_USER=qq email
EMAIL_HOST_PASSWORD=qq邮箱密码
```
具体配置是在：
https://github.com/liangliangyy/DjangoBlog/blob/master/DjangoBlog/settings.py#L195
