### ISSUE TITLE
文章导入功能

### ISSUE THREAD

**Issue by LeiyuanBlog** [liangliangyy/DjangoBlog#515]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x ] 添加新的特性或者功能
- [ x] 请求技术支持

hi～我没有找到文章的导入功能。是否有考虑新增多md文件导入功能，可以更加便捷的将之前的文档导入网站

**Comment by liangliangyy** [comment]
你好，暂时没有规划这个功能。因为和文章相关的信息有点多，而且没办法统一md文件的格式。
