### ISSUE TITLE
没有预览图吗?

### ISSUE THREAD

**Issue by Youkii-Chen** [liangliangyy/DjangoBlog#516]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----
- [x] 添加新的特性或者功能

建议在 Readme 中添加项目的预览图, 以助于新来的访问者更好地了解项目.

**Comment by liangliangyy** [comment]
你好，没有预览图。可以访问我的网站 https://lylinux.net/ 来查看效果。

**Comment by Youkii-Chen** [comment]
你好，对你的项目很感兴趣，是否有换主题相关的接口和功能呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月1日(周一) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liangliangyy/DjangoBlog] 没有预览图吗? (Issue #516)




 
你好，没有预览图。可以访问我的网站 https://lylinux.net/ 来查看效果。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Youkii-Chen** [comment]
如果您愿意，我可以参加一起开发维护

**Comment by liangliangyy** [comment]
可以呀，欢迎欢迎。

**Comment by Youkii-Chen** [comment]
方便留个联系方式吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月1日(周一) 下午2:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liangliangyy/DjangoBlog] 没有预览图吗? (Issue #516)




 
可以呀，欢迎欢迎。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liangliangyy** [comment]
可以联系我的邮箱： liangliangyy#gmail.com
