### ISSUE TITLE
两个html的bug

### ISSUE THREAD

**Issue by donghj2000** [liangliangyy/DjangoBlog#518]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持
1，templates\blog\tags\article_info.html 的第26行，是不是应该为 {% if article.comment_set and article.comment_set.count %} ？
![image](https://user-images.githubusercontent.com/84324399/141270060-86438889-1eab-493f-be0b-7a1bdc5e5616.png)

2，templates\blog\tags\sidebar.html 的第125行是不是应该为 <li><a href="{% url "account:login" %}" rel="nofollow">登录</a></li> ？
![image](https://user-images.githubusercontent.com/84324399/141269918-e023207e-5264-4552-b837-17d650a9d3bb.png)

**Comment by donghj2000** [comment]
第2个bug为 <li><a href="{% url "account:login" %}" rel="nofollow">登录</a></li>

**Comment by liangliangyy** [comment]
感谢提醒，已经修复。
