### ISSUE TITLE
评论不支持markdown编辑框

### ISSUE THREAD

**Issue by donghj2000** [liangliangyy/DjangoBlog#521]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

评论不能实时显示markdown编辑框，对不懂的人来说，手动敲语法格式不友好。
可以加上去，和后台编辑一样。
post_comment.html
![image](https://user-images.githubusercontent.com/84324399/141598942-582765ce-6b1f-45bd-974d-68373c0da183.png)
blog.js
![image](https://user-images.githubusercontent.com/84324399/141598960-246fb7eb-63aa-47cb-9c83-c383b7874bd5.png)
效果
![image](https://user-images.githubusercontent.com/84324399/141599197-fa0937e1-da8d-4fc6-974d-704471a8b515.png)

**Comment by liangliangyy** [comment]
这个暂时不需要，因为评论格式要求没那么严格，增加一个markdown编辑器反倒使得界面很臃肿。
