### ISSUE TITLE
首页功能 如何添加新的链接

### ISSUE THREAD

**Issue by PengHui-pwld** [liangliangyy/DjangoBlog#522]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

非常感谢您的贡献，我想请教您一个问题 首页中 【功能】部分 我如何自己添加新的链接，目前有【刷新缓存】
【运动轨迹记录】【GitBook】感谢您的回复

**Comment by liangliangyy** [comment]
这个暂时不支持配置，可以自行修改代码来添加
