### ISSUE TITLE
文章只是点播视频吗？

### ISSUE THREAD

**Issue by glinxx** [liangliangyy/DjangoBlog#525]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by glinxx** [comment]
可以的，用iframe。

**Comment by Gwenhaell** [comment]
> 可以的，用iframe。

这只能自己后端手动添加吧，在文章编辑页面貌似不行
当然我很菜，希望指导
