### ISSUE TITLE
	 Database returned an invalid datetime value. Are time zone definitions for your database installed?

### ISSUE THREAD

**Issue by biggerl** [liangliangyy/DjangoBlog#527]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by SmileLeev** [comment]
确认settings.py下：USE_TZ=False
确认mysql时区设置

**Comment by gzwxh** [comment]
我这边部署也遇到这个问题了，解决方案是将
 /etc/init.d/memcached stop
这个管理服务进行重启一下，需要注意，重启的时候可能没有生效，你可以停止的时候看一下是否可以前端是否可以访问

**Comment by dlb-shy** [comment]
USE_TZ=False 改下这个就可以了下载的项目这个默认为True

**Comment by MrChengCun** [comment]
佬，后面可以出套这样的视频课程？
