### ISSUE TITLE
功能确实

### ISSUE THREAD

**Issue by lmafeifeil** [liangliangyy/DjangoBlog#529]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x ] 添加新的特性或者功能
- [ ] 请求技术支持

1 为用户勾选‘工作人员状态’后，该用户也无法访问管理页面
2 超级用户无法创建用户组

**Comment by liangliangyy** [comment]
1. 用户需要是超级用户 才可以访问后台。
2. 本项目中没有用户组的概念。

**Comment by lmafeifeil** [comment]
1
![image](https://user-images.githubusercontent.com/95956841/146389203-8916fd3a-24f4-4bd9-8e80-d0cc271f325f.png)

2![image](https://user-images.githubusercontent.com/95956841/146388753-9e856bea-ff2e-4ba2-9f85-255f040dc5b8.png)
BlogUser表下的数据项‘group’  与auth.Group表关系为多对多 
related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'

**Comment by lmafeifeil** [comment]
![image](https://user-images.githubusercontent.com/95956841/146389498-6d18112d-fcb8-47ab-ba72-bf913b15f038.png)

**Comment by liangliangyy** [comment]
1.  https://github.com/liangliangyy/DjangoBlog/blob/master/djangoblog/admin_site.py#L27
2.  是有group的relation，但是没有使用，本项目设计之初是个人站点，未考虑多人的情况。

**Comment by lmafeifeil** [comment]
太感谢了

**Comment by lmafeifeil** [comment]
请问这个项目的前端技术，后端技术，和中间件技术分别是什么？

**Comment by liangliangyy** [comment]
没前端技术，使用的是django自带的模板渲染出来的，中间件是 memcach，es，mysql。

**Comment by lmafeifeil** [comment]
太感谢了我的实验报告有救了。感谢感谢

**Comment by lmafeifeil** [comment]
寒假学完django我再改改。谢谢大救星
