### ISSUE TITLE
docker部署的 管理员密码是啥呢

### ISSUE THREAD

**Issue by xmlgrg** [liangliangyy/DjangoBlog#533]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by dhr2333** [comment]
在初始化的时候有让你填写用户密码，是你自己定义的

**Comment by xmlgrg** [comment]
好的，谢谢
