### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [liangliangyy/DjangoBlog#537]
Hey there!

I belong to an open source security research community, and a member (@ktg9) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by liangliangyy** [comment]
you can contact me via my email: liangliangtt#gmail.com.
thanks.

**Comment by JamieSlome** [comment]
@liangliangyy - you should have received an e-mail yesterday! ❤️ 

Just for reference, you can find the report here:

https://huntr.dev/bounties/2bb5be32-b318-4a5c-9508-dea02fa68980/

**Comment by liangliangyy** [comment]
I will remove this URL. thanks.
