### ISSUE TITLE
服务器部署时出现错误error: <class 'socket.error'>, [Errno 111] Connection refused: file: /usr/lib/python2.7/socket.py line: 228

### ISSUE THREAD

**Issue by wendao365** [liangliangyy/DjangoBlog#540]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ x] 请求技术支持
前面的步骤都成功了，到这步过不去了
(djangoblog) ubuntu@VM-0-6-ubuntu:~/python$ sudo supervisorctl update
error: <class 'socket.error'>, [Errno 111] Connection refused: file: /usr/lib/python2.7/socket.py line: 228

**Comment by liangliangyy** [comment]
可能是supervisord 没启动或者启动失败了。

**Comment by wendao365** [comment]
您好：
&nbsp; &nbsp; &nbsp;站点部署是好了，但网页打开格式不太对，请问会是什么情况，谢谢







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liangliangyy/DjangoBlog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月25日(星期二) 上午10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liangliangyy/DjangoBlog] 服务器部署时出现错误error: <class 'socket.error'&gt;, [Errno 111] Connection refused: file: /usr/lib/python2.7/socket.py line: 228 (Issue #540)





 
可能是supervisord 没启动或者启动失败了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lingchen218** [comment]
开发不是 python3.8吗？为啥要用旧版本的python？
