### ISSUE TITLE
博客渲染不出公式

### ISSUE THREAD

**Issue by ErzhongHoo** [liangliangyy/DjangoBlog#541]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

# 问题：渲染不出公式！

mdeditor编辑器渲染效果
![mdeditor编辑器渲染效果](https://ezhonghublog.oss-cn-shenzhen.aliyuncs.com/%E7%BC%96%E8%BE%91%E5%99%A8%E7%94%BB%E9%9D%A2.png?versionId=CAEQKRiBgID3qOnu9BciIDkwZTE4ZjkzMjEyMTRhNDY4YTlhZGMzNjQyMTFhMzQw)

博客渲染效果
![博客渲染效果](https://ezhonghublog.oss-cn-shenzhen.aliyuncs.com/html%E6%B8%B2%E6%9F%93%E7%94%BB%E9%9D%A2.png?versionId=CAEQKRiBgMCMqenu9BciIGU2MmExZWUyZjBhMzQzNGQ5ZGI3YTI4ODIyNmZmZDMy)

---
自己找不出原因在哪。望求解！！

**Comment by comingboy0701** [comment]
1. mardow 转HTML 配置 mdx_math 
md = markdown.Markdown(
            extensions=[
                'mdx_math',
                'extra',
                'codehilite',
                'toc',
                'tables',
                # 'pymdownx.caret',
            ],
            extension_configs={
            'mdx_math': {'enable_dollar_delimiter': True},
            }
        )
2.前端展示配置 
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML' async></script>
