### ISSUE TITLE
Tag 功能没完成？

### ISSUE THREAD

**Issue by xmyangz** [liangliangyy/DjangoBlog#55]
一旦添加任何 Tag，页面就出错，删光所有 Tag 就正常了。

**Comment by liangliangyy** [comment]
添加Tag会出错? 我这里还真没遇到过,麻烦贴下详细的错误信息哈.

**Comment by xmyangz** [comment]
Request Method: | GET
-- | --
http://localhost:5000/article/2017/12/7/3.html
1.11.5
ZeroDivisionError
float division by zero
/Users/yangz/Documents/Dev/Python/DjangoBlog/blog/templatetags/blog_tags.py in <lambda>, line 141
/Users/yangz/anaconda3/bin/python
3.6.3

**Comment by liangliangyy** [comment]
貌似是除0报错,
```python
if tags and len(tags) > 0:
        s = list(map(lambda t: (t, t.get_article_count()), tags))
        count = sum(map(lambda t: t[1], s))
        dd = count / len(tags)
        sidebar_tags = list(map(lambda x: (x[0], x[1], (x[1] / dd) * increment + 10), s))
```
是
`dd = count / len(tags)`
这里报错的吗?
但是我上面是有判断的,
麻烦看看你的代码是不是和我的代码是同步的,另外如果还有错误的话麻烦贴下错误堆栈信息,另外麻烦打印下这里的各个变量看下.

**Comment by liangliangyy** [comment]
大概知道了,可能是dd这个变量是0,也就是count这个变量是0,麻烦你打印下看看是不是这个原因,我晚点修复下,谢谢.

**Comment by xmyangz** [comment]
是的，我加了一个判断
if dd == 0:
    dd = 1
就正常了

**Comment by xmyangz** [comment]
另外，在微信里命令可以执行，但是文章点击进去就报404，请问还需要配置哪里吗？
还有，希望在便捷登录增加微信和QQ登录，文章增加分享到微信、QQ、微博等功能。如果能全局替换主题就更好了。

**Comment by liangliangyy** [comment]
404的话看看`Site.objects.get_current().domain`的输出，如果不对的话要配置下site就可以了。
微信的话因为要企业认证，所以微信的相关功能不是很完善。分享功能和QQ登录后续会加上的，敬请期待，
另外欢迎提pr。😁😁

**Comment by xmyangz** [comment]
是域名不对，微信文章链接、sitemap、RSS 里面都是“example.com"，请问可以在 settings 里统一设置域名吗？或者把域名设置成SITE_URL也可以。

**Comment by liangliangyy** [comment]
在后台的站点配置中，将默认站点的修改为你的地址就可以了。

**Comment by scholarg** [comment]
我也发现了这个错误
