### ISSUE TITLE
nginx+uwsgi 部署完无法访问

### ISSUE THREAD

**Issue by dev-Duchangjiang** [liangliangyy/DjangoBlog#556]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持
  这是我的配置文件

![截屏2022-03-02 下午7 21 47](https://user-images.githubusercontent.com/65998702/156354884-0b17c325-22b4-4922-9ea2-875438882231.png)
![截屏2022-03-02 下午7 22 01](https://user-images.githubusercontent.com/65998702/156354892-e4fcff8a-a6a6-4db5-9479-20d0b68b7c66.png)
![截屏2022-03-02 下午7 23 22](https://user-images.githubusercontent.com/65998702/156354896-0632fc67-83e2-43c9-b2a0-bf506d321722.png)

**Comment by liangliangyy** [comment]
部署请参考：
https://www.lylinux.net/article/2019/8/5/58.html
