### ISSUE TITLE
启动项目报错：NameError: name '_mysql' is not defined

### ISSUE THREAD

**Issue by Yangchenguang0** [liangliangyy/DjangoBlog#557]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

启动报错

![image](https://user-images.githubusercontent.com/32182275/157578068-826f74e8-a1bc-49a8-8b28-80b88a9fbedb.png)

已安装的模块

![image](https://user-images.githubusercontent.com/32182275/157578156-3d169f8a-5302-49f9-bf66-2d488ea11c40.png)

**Comment by Yangchenguang0** [comment]
settings.py的设置

![image](https://user-images.githubusercontent.com/32182275/157578429-a893a401-17eb-4bd8-aa13-eeafa8916e04.png)

**Comment by liangliangyy** [comment]
请参考:
https://stackoverflow.com/questions/63109987/nameerror-name-mysql-is-not-defined-after-setting-change-to-mysql

**Comment by Yangchenguang0** [comment]
> 请参考: https://stackoverflow.com/questions/63109987/nameerror-name-mysql-is-not-defined-after-setting-change-to-mysql

谢谢，已解决
