### ISSUE TITLE
1146, "Table 'djangoblog.django_site' doesn't exist"

### ISSUE THREAD

**Issue by 15210859049** [liangliangyy/DjangoBlog#559]
添加文章的时候为什么提示这个：1146, "Table 'djangoblog.django_site' doesn't exist"
我看着Models中也没有site这个model啊

**Comment by liangliangyy** [comment]
请确认database migration 是否执行成功。

**Comment by 15210859049** [comment]
确实执行完了啊

**Comment by liangliangyy** [comment]
你修改代码了吗？
确认下是否有这个
https://github.com/liangliangyy/DjangoBlog/blob/master/djangoblog/settings.py#L49

**Comment by 15210859049** [comment]
添加文章的的那个方法，是写在views的哪个方法中了啊？

**Comment by 15210859049** [comment]
添加文章的的那个方法，是写在views的哪个方法中了啊？是在/admin/blog/article/add/ 这个方法了吗

**Comment by BFD2018** [comment]
紫荆花已收到您的邮件！
