### ISSUE TITLE
documents.py  bug

### ISSUE THREAD

**Issue by donghj2000** [liangliangyy/DjangoBlog#564]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持
楼主你好，documents.py 中，这一行是不是错了：                author={
                    '**nikename**': article.author.username,
                    'id': article.author.id},

应该是nickname吧？

**Comment by liangliangyy** [comment]
是的，这里拼错了，感谢提醒。
