### ISSUE TITLE
添加分类，添加文章，不支持中文，输入中文，就报错

### ISSUE THREAD

**Issue by sunguotao** [liangliangyy/DjangoBlog#58]
Request Method: | POST
-- | --
http://127.0.0.1:8000/admin/blog/category/3/change/
1.11.7
InternalError
(1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")
/Users/sunguotao/Desktop/Python/DjangoBlog/env/lib/python3.6/site-packages/pymysql/err.py in raise_mysql_exception, line 107
/Users/sunguotao/Desktop/Python/DjangoBlog/env/bin/python
3.6.3
['/Users/sunguotao/Desktop/Python/DjangoBlog',  '/Users/sunguotao/Desktop/Python/DjangoBlog/env/lib/python36.zip',  '/Users/sunguotao/Desktop/Python/DjangoBlog/env/lib/python3.6',  '/Users/sunguotao/Desktop/Python/DjangoBlog/env/lib/python3.6/lib-dynload',  '/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6',  '/Users/sunguotao/Desktop/Python/DjangoBlog/env/lib/python3.6/site-packages']
星期四, 14 十二月 2017 21:42:55 +0800

**Comment by liangliangyy** [comment]
```sql
CREATE DATABASE `djangoblog` /*!40100 DEFAULT CHARACTER SET utf8 */
```
创建数据库时请使用utf8字符集.

**Comment by sunguotao** [comment]
ok , 已经解决了！
