### ISSUE TITLE
因为误操作删除 Site 配置后会导致整个站点随机崩溃，且没有错误提示

### ISSUE THREAD

**Issue by lovexuan** [liangliangyy/DjangoBlog#589]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

## 错误详情

因为误操作删除 Site 配置后会导致整个站点随机崩溃（如无法新建 Blog 等），开启 Debug 模式追踪到出错的行在 ``djangoblog/utils.py`` 中的 ``Site.objects.get_current()``。但在我尝试重新添加 Site 配置后依然没有恢复，追溯源码发现需要把新建的 Site 配置的 id 设置为 1，admin 页面无此选项，必须登录数据库后台操作，这对于大多数初级建站用户较为困难。

## 建议

* 禁止删除 Site 配置，只允许修改。
* 在新建 blog 等操作时如果找不到 Site 配置需要更友好的错误提示。
* 新建的 Site 配置 id 强制设定为 1。

**Comment by lovexuan** [comment]
顺便问一下，昵称是在哪里修改？我都是直接操作数据库的……

**Comment by liangliangyy** [comment]
你好，siteid设置是在：
https://github.com/liangliangyy/DjangoBlog/blob/master/djangoblog/settings.py#L201
另昵称可以在admin后台修改。

**Comment by lovexuan** [comment]
> 你好，siteid设置是在： https://github.com/liangliangyy/DjangoBlog/blob/master/djangoblog/settings.py#L201 另昵称可以在admin后台修改。

* siteid 设置找到了，但还是建议添加一个更友好的提示信息
* 昵称仍然没有找到，求指路
* 另外还发现了一个新问题，Django 的错误邮件（_[Django] ERROR ..._）似乎没有记入邮件发送日志中，里面只看到了用户的注册验证邮件（_验证您的电子邮箱_）

**Comment by liangliangyy** [comment]
邮件发送日志是只记录了用户注册相关的发送记录。
