### ISSUE TITLE
按照说明操作，显示页面报错：数据库返回了无效的datetime值。是否安装了数据库的时区定义？

### ISSUE THREAD

**Issue by icesharp107** [liangliangyy/DjangoBlog#594]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by icesharp107** [comment]
上网查了，改配置文件，USE_TZ = False
https://blog.csdn.net/weixin_45719821/article/details/123405127

**Comment by yanhuixie** [comment]
你要做的是往mysql里灌入时区数据。
1. Populate the timezone definitions in the 'mysql' table
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql

2. Flush tables
mysql -u root -p -e "flush tables;" mysql 

3. Restart mysql（通常不做也行）
sudo service mysql restart

https://stackoverflow.com/questions/21351251/database-returned-an-invalid-value-in-queryset-dates/21571350#21571350
