### ISSUE TITLE
百度统计部分如何添加能否给一个说明，代码检查显示referrer被禁用？

### ISSUE THREAD

**Issue by zyan-repository** [liangliangyy/DjangoBlog#600]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持
在管理员后台->网站配置->网站统计代码，把百度统计上给的代码贴进去保存，再去百度统计代码检查显示referrer被禁用，页面上点击百度统计显示500错误

**Comment by liangliangyy** [comment]
请贴下你的网址看看。

**Comment by 13681017963** [comment]
> 请贴下你的网址看看。

[](http://www.hogking.cn/)
管理界面网站配置处的网站统计代码如下，没有正常工作
```
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?687c87f97c3fb38ee07523f906de7367";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
```
百度统计上代码检查报错如题

**Comment by zyan-repository** [comment]
已解决
