### ISSUE TITLE
django.db.utils.OperationalError: (2005, "Unknown server host 'host' (11001)")这个问题怎么解决

### ISSUE THREAD

**Issue by hdd-11** [liangliangyy/DjangoBlog#603]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by nongreen** [comment]
@hdd-11 您需要在文件 'djagoblog/settings.py' 中设置数据库设置。 如果您将使用 mysql，则需要创建新数据库并设置 djangoblog 设置以使用该数据库。 如果您将使用 sqlLite，您需要在数据库设置中指定它

在这里的 'djangoblog/settings.py' 中有设置。

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DJANGO_MYSQL_DATABASE') or 'djangoblog',
        'USER': os.environ.get('DJANGO_MYSQL_USER') or 'root',
        'PASSWORD': os.environ.get('DJANGO_MYSQL_PASSWORD') or 'djangoblog_123',
        'HOST': os.environ.get('DJANGO_MYSQL_HOST') or '127.0.0.1',
        'PORT': int(
            os.environ.get('DJANGO_MYSQL_PORT') or 3306),
        'OPTIONS': {
            'charset': 'utf8mb4'},
    }}
```
