### ISSUE TITLE
SEO优化: 允许为每个文章设置自定义固定链接

### ISSUE THREAD

**Issue by XiaFanGit** [liangliangyy/DjangoBlog#608]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

因为是搬迁博客的行为很常见，所以希望文章的展示能和之前的一样，而且像目前这样使用日期的文章链接不利于 SEO

**Comment by liangliangyy** [comment]
你好，这个可以自行修改
https://github.com/liangliangyy/DjangoBlog/blob/master/blog/urls.py
