### ISSUE TITLE
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

### ISSUE THREAD

**Issue by naiyouweibaomihua** [liangliangyy/DjangoBlog#615]
数据库迁移到一半的时候这样提示，google了一下发现是字段长度限制的原因，但是不知道该怎么改

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by naiyouweibaomihua** [comment]
把mysql5.6升级到5.7，问题解决了

**Comment by naiyouweibaomihua** [comment]
但是还是不知道怎么调低字段长度，希望有会的大佬能回答一下，蟹蟹

**Comment by liangliangyy** [comment]
修改model里面对应字段长度，然后重新执行数据库迁移即可。
