### ISSUE TITLE
docker方式启动容器会自动退出

### ISSUE THREAD

**Issue by wilikeit** [liangliangyy/DjangoBlog#617]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

环境：
系统：centos7.6
docker版本：1.13.1
docker-compose 版本：docker-compose version 1.25.5, build 8a1c60f6

现象：
按照下面的方式，改成 自己相应的mysql参数后，启动后，过几秒，容器就自动退出了
docker run -d -p 8000:8000 -e DJANGO_MYSQL_HOST=mysqlhost -e DJANGO_MYSQL_PASSWORD=mysqlrootpassword -e DJANGO_MYSQL_USER=root -e DJANGO_MYSQL_DATABASE=djangoblog --name djangoblog liangliangyy/djangoblog:latest
换成docker-compose 方式报下面错
ERROR: Could not build wheels for gevent, which is required to install pyproject.toml-based projects
ERROR: Service 'djangoblog' failed to build: The command '/bin/sh -c pip install --upgrade pip && pip install -Ur requirements.txt && pip install gunicorn[gevent] && pip cache purge' returned a non-zero code: 1

**Comment by liangliangyy** [comment]
使用最新代码重新构建下，python3.11 gevent还不支持python3.11。

**Comment by wilikeit** [comment]
换了新版本再docker-compose可以了，没报错，但是用docker run -d -p 8000:8000 -e DJANGO_MYSQL_HOST=mysqlhost容器会退出的原因我调试了下，你看对不对，如下：

我看代码settins.py 中是用'HOST': os.environ.get('DJANGO_MYSQL_HOST') or '127.0.0.1'
我看容器启动后，容器中报错是：django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '127.0.0.1' (115)")

但mysql在windows上，djangoblog部署在linux就报错了，如果mysql在linux上估计也不会有会问题

感觉没接收到外部参数-e DJANGO_MYSQL_HOST

**Comment by liangliangyy** [comment]
这个不会的，我使用docker run 测试过了，是可以运行的。
