### ISSUE TITLE
首页搜索有时搜索不到

### ISSUE THREAD

**Issue by wilikeit** [liangliangyy/DjangoBlog#618]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

现象描述 ：
文章内容如下：
var1,var2=1,2
#5555555

我搜索 5555555 能搜索到，但搜索 55 却搜索不到，搜索 1,2 也搜索不到
文章搜索是根据  ”包含“来搜索的吗？

**Comment by wilikeit** [comment]
是用分词搜索 的吗？

**Comment by liangliangyy** [comment]
是分词搜索的，用的结巴分词。
