### ISSUE TITLE
是否新增网站访客数量统计功能

### ISSUE THREAD

**Issue by ch3nnn** [liangliangyy/DjangoBlog#632]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

是否可以新增网站访客数量统计  
例如 [“不蒜子”](http://ibruce.info/2015/04/04/busuanzi/#more)   区别与百度统计谷歌分析可直接将访问次数显示在网页上（也可不显示）
<img width="978" alt="image" src="https://user-images.githubusercontent.com/40114564/216553487-605ed45b-ef60-43c8-8416-3e63221b50ec.png">

效果如上图,  觉得可行我可以提 PR

**Comment by liangliangyy** [comment]
你好，感谢你的建议，这个功能没必要引入第三方的组件。

**Comment by ch3nnn** [comment]
好的
