### ISSUE TITLE
如何修改主页左上角的“djangoblog”“基于Django的博客系统”

### ISSUE THREAD

**Issue by qdwangjianjun** [liangliangyy/DjangoBlog#634]
![1676021829401](https://user-images.githubusercontent.com/40756962/218056929-74a4e244-5a46-4d9a-a733-4f3ad0e76805.jpg)

如何修改主页左上角的“djangoblog”“基于Django的博客系统”？

我修改了无效
            setting.sitename = 'djangoblog'
            setting.site_description = '个人主页'
            setting.site_seo_description = '个人主页'

**Comment by liangliangyy** [comment]
在后台的网站设置里。
https://github.com/liangliangyy/DjangoBlog/blob/master/blog/models.py#L298
