### ISSUE TITLE
能否把 pagedown 替换成 markdownx

### ISSUE THREAD

**Issue by xmyangz** [liangliangyy/DjangoBlog#64]
pagedown 不能上传图片，基本上没有实用价值了。如果能在编辑器集成一个简单的工具条（类似 git 这个），就更好了！

**Comment by liangliangyy** [comment]
感谢你的建议，不过我自己一般都是在电脑上用markdown编辑器写好之后直接在后台粘贴进去的，对于图片来说其实是有集成一个简单的图床功能的。所以可能后台的编辑器近期是不会改动的，后面等功能基本都完善之后可能会修改下编辑器，再次感谢你的建议。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
