### ISSUE TITLE
请问对接memcached部分是那个配置文件啊

### ISSUE THREAD

**Issue by txbxxx** [liangliangyy/DjangoBlog#641]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x ] 请求技术支持

**Comment by liangliangyy** [comment]
https://github.com/liangliangyy/DjangoBlog/blob/master/docs/config.md
https://docs.djangoproject.com/en/4.1/topics/cache/
