### ISSUE TITLE
作者你好，你的项目存在安全漏洞

### ISSUE THREAD

**Issue by thebatmanfuture** [liangliangyy/DjangoBlog#663]
https://github.com/liangliangyy/DjangoBlog
你的这个项目的最新版存在漏洞：我给出的修复方案如下，看到望回复😋，详情如下
https://batmanfuture.cn/2023/05/28/github-5-5k-star的django项目的代码审计/
后续如果联系我可以加我qq:1601749085

**Comment by liangliangyy** [comment]
感谢对本项目的关注，提到的相关漏洞以FIX。
