### ISSUE TITLE
docker部署遇到一些问题

### ISSUE THREAD

**Issue by uncleYiba** [liangliangyy/DjangoBlog#669]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [×] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [404] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [×] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [×] 请求技术支持

参考 https://github.com/liangliangyy/DjangoBlog/blob/master/docs/docker.md 进行docker部署  
使用docker-compose进行部署  
A  使用 docker-compose build  自行build djangoblog镜像，但是犹豫网络或者源的原因卡在了  
    Downloading Django-4.2.3-py3-none-any.whl (8.0 MB)  
    这一步，导致无法进行下去，切换了豆瓣源进行尝试显示没有Django-4.2.3  
B  使用docker run部署方式提供的djangoblog，修改yml文件进行docker-compose部署  
   创建好用户之后，访问ip:80的服务之后，djangoblog容器日志显示如下错误  
File "/usr/local/lib/python3.11/site-packages/django/utils/timezone.py", line 82, in get_default_timezone  
    return zoneinfo.ZoneInfo(settings.TIME_ZONE)

**Comment by liangliangyy** [comment]
A. 国内请使用阿里源
B. 类似这样的报错新版本已经做了修复，请使用最新代码重新构建。
