### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by notjiangjiu** [liangliangyy/DjangoBlog#675]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [X] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [X] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [X] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [X] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

# 我是直接在win10中运行代码，执行python manage.py makemigrations时，报错，ModuleNotFoundError：No module name 'mdeditor'，其实注册的app中'mdeditor','haystack', 'compressor'都会报错
# 我在项目根目录没有发现这些app

**Comment by mdehsan873** [comment]
@notjiangjiu Hi could you please elaborate more in English I don't know this language. I want to contribute to this repo.

**Comment by liangliangyy** [comment]
Make sure all your dependencies are installed successfully
