### ISSUE TITLE
sidebar bug: when not commented in template, this does not render.

### ISSUE THREAD

**Issue by jonascarvalh** [liangliangyy/DjangoBlog#682]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [X] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [X] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

![image](https://github.com/liangliangyy/DjangoBlog/assets/79672134/2e54bbef-4971-4ef5-981a-a82a30d52181)

![image](https://github.com/liangliangyy/DjangoBlog/assets/79672134/a744c714-9d6f-4a6c-9722-a1d840d8ba83)

**Comment by liangliangyy** [comment]
This error is not caused by the  comments, but by the settings of mysql, please refer to
https://stackoverflow.com/questions/21351251/database-returned-an-invalid-value-in-queryset-dates/21571350#21571350

**Comment by Matsumotosenki** [comment]
USE_TZ=False 改下这个就可以了下载的项目这个默认为True
以前有过一篇这个的讨论
https://github.com/liangliangyy/DjangoBlog/issues/527
