### ISSUE TITLE
请问现在只能支持8以上的mysql了吗？我5.7无法安装

### ISSUE THREAD

**Issue by kenuoseclab** [liangliangyy/DjangoBlog#683]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by rockyshen** [comment]
django v4.x.x版本只支持V8版本的mysql，如果要支持mysql V5.7版本，需要安装：`pip install django==3.2.4

**Comment by Matsumotosenki** [comment]
4.0是支持mysql5.7版本的
https://stackoverflow.com/questions/75986754/django-db-utils-notsupportederror-mysql-8-or-later-is-required-found-5-7-33

**Comment by Lingchen218** [comment]
> django v4.x.x版本只支持V8版本的mysql，如果要支持mysql V5.7版本，需要安装：`pip install django==3.2.4

使用低版本的django 可以兼容吗？会不会有安全漏洞？

**Comment by Lingchen218** [comment]
> 4.0是支持mysql5.7版本的 https://stackoverflow.com/questions/75986754/django-db-utils-notsupportederror-mysql-8-or-later-is-required-found-5-7-33

django 4.0.4 有函数参数漏洞
