### ISSUE TITLE
css

### ISSUE THREAD

**Issue by Autism-mm** [liangliangyy/DjangoBlog#685]
![WNO)}Y22)Y$4H%1PY OJUIP](https://github.com/liangliangyy/DjangoBlog/assets/58109255/e6590e51-cff0-447e-b07e-e27c62cd1c6e)
![tu](https://github.com/liangliangyy/DjangoBlog/assets/58109255/6f4e8aa2-17cf-4e49-b38d-4f6399e465d5)
这个问题应该是static在blog下级文件夹，不知道怎么改路径

**Comment by liangliangyy** [comment]
请执行
./manage.py compress --force

请仔细阅读部署文档。
