### ISSUE TITLE
如何自定义后端页面，1.0.0.7文件我翻了一圈，没有找到与后端页面相关的html文件

### ISSUE THREAD

**Issue by Matsumotosenki** [liangliangyy/DjangoBlog#686]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [X] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [X] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [X] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [X] 请求技术支持

**Comment by liangliangyy** [comment]
请参考django admin的文档哈
