### ISSUE TITLE
求助Debug = False后所有静态文件丢失

### ISSUE THREAD

**Issue by Matsumotosenki** [liangliangyy/DjangoBlog#688]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by liangliangyy** [comment]
请参考 https://docs.djangoproject.com/en/dev/howto/static-files/#serving-static-files-in-development

**Comment by Matsumotosenki** [comment]
> 请参考 https://docs.djangoproject.com/en/dev/howto/static-files/#serving-static-files-in-development
谢谢大佬！
