### ISSUE TITLE
win11 本地部署完成后首页进不去，后台可以进去

### ISSUE THREAD

**Issue by Lingchen218** [liangliangyy/DjangoBlog#693]
![image](https://github.com/liangliangyy/DjangoBlog/assets/48959004/7106b502-a9e4-42d5-9301-d1a903d82a52)
![image](https://github.com/liangliangyy/DjangoBlog/assets/48959004/aeed1df0-a350-4bc8-b720-b3235c542e60)
![image](https://github.com/liangliangyy/DjangoBlog/assets/48959004/d2ec1b59-028b-4953-8d96-8f91ff142a7a)

**Comment by CITy12388** [comment]
在settings中把USE_TZ=TRUE改为FALSE

**Comment by Lingchen218** [comment]
> 在settings中把USE_TZ=TRUE改为FALSE

感谢大佬，解决了.
