### ISSUE TITLE
做完一系列步骤后，运行代码后网页404

### ISSUE THREAD

**Issue by Diu07** [liangliangyy/DjangoBlog#714]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

已经按照readme的步骤做了，最后运行代码网页出现了404，这是什么问题？
<img width="841" alt="联想截图_20240522233016" src="https://github.com/liangliangyy/DjangoBlog/assets/139679479/46730c2f-dee5-458b-ad79-b37021e1110e">

<img width="1280" alt="联想截图_20240522233621" src="https://github.com/liangliangyy/DjangoBlog/assets/139679479/68481533-7305-4c0b-8185-4168c9496fc4">

**Comment by liangliangyy** [comment]
你是改了什么东西吗？检查下你的urls的配置

**Comment by Diu07** [comment]
重新操作了一遍，可以运行了
