### ISSUE TITLE
我成功的死在了mysqlclient安装上，放弃了

### ISSUE THREAD

**Issue by chailishen** [liangliangyy/DjangoBlog#716]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by liangliangyy** [comment]
你可以把你遇到的问题贴出来，大家可以帮你看看

**Comment by Diu07** [comment]
推荐看下尚硅谷的mysql

**Comment by bioinfotec** [comment]
安装mysqlclient前需要先安装下面的依赖项：
sudo apt install libmysqlclient-dev
sudo apt install build-essential
sudo apt install pkg-config
