### ISSUE TITLE
Google 和 GitHub oauth 登录无法正确返回参数

### ISSUE THREAD

**Issue by Plutoeat** [liangliangyy/DjangoBlog#717]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

google 和 github oauth 登录均无法进行授权，怀疑是对 post 的代理做了检测，有代理无法正确返回，我用 postman 可以正确返回access_token 等数据

**Comment by Diu07** [comment]
解决了这个，还有一个是注册时登录消息没有发送到邮箱(18296591578@163.com)。

**Comment by Plutoeat** [comment]
好的，解决了，是我post携带数据方式错了，谢谢
