### ISSUE TITLE
请问这个mysql数据库在哪里啊

### ISSUE THREAD

**Issue by horizon-xt** [liangliangyy/DjangoBlog#719]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by jiangchangxiao** [comment]
不是docker安装的话，好像需要自己下载一个。
安装后要修改mysql的时区，
`mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql`

`mysql -u root -p -e "SET GLOBAL time_zone = '+00:00';"`

`service mysql restart`
