### ISSUE TITLE
数据库连接设置为localhost而不是host，作者的需要修改一下

### ISSUE THREAD

**Issue by Jiangfengyuh** [liangliangyy/DjangoBlog#721]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by liangliangyy** [comment]
感谢反馈，具体是指哪里呢？

**Comment by Jiangfengyuh** [comment]
在Readme文件的settings数据库地址配置，host应该改为localhost，若您本意为host不是本地地址而是代指数据库泛地址，需要自己再次进行修改，那么抱歉误解打扰
![5d3b9713419a2dd7418c222b8932f7ab](https://github.com/liangliangyy/DjangoBlog/assets/112694331/51456c79-0271-4576-a8af-98a9aed27278)

**Comment by Jiangfengyuh** [comment]
在Readme文件的settings数据库地址配置，host应该改为localhost，若您本意为host不是本地地址而是代指数据库泛地址，需要自己再次进行修改，那么抱歉误解打扰
![5d3b9713419a2dd7418c222b8932f7ab](https://github.com/liangliangyy/DjangoBlog/assets/112694331/51456c79-0271-4576-a8af-98a9aed27278)
