### ISSUE TITLE
只支持mysql8.0+吗

### ISSUE THREAD

**Issue by kitzza** [liangliangyy/DjangoBlog#725]
我mysql5.7版本，
django.db.utils.NotSupportedError: MySQL 8 or later is required (found 5.7.37)

**Comment by kitzza** [comment]
已解决。

**Comment by yuanshangyujingshierlou** [comment]
> 已解决。

咋解决的噢

**Comment by kitzza** [comment]
> > 已解决。
> 
> 咋解决的噢

django版本降低为 == 3.2.4，然后settings.py里面有个变量 USE_TZ = True 改成 False。就行了
