### ISSUE TITLE
为什么出现这个错误啊

### ISSUE THREAD

**Issue by Zixuiu** [liangliangyy/DjangoBlog#729]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

![image](https://github.com/liangliangyy/DjangoBlog/assets/105110952/ddebafdb-8470-42aa-9eb7-a551c5938217)

**Comment by Junnstoy** [comment]
#594 把这个在setting里改成false
