### ISSUE TITLE
我部署的时候一直报错，报一个数据区时区的错误，搞不定，Error during template rendering

### ISSUE THREAD

**Issue by ownerorall** [liangliangyy/DjangoBlog#739]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by liangliangyy** [comment]
更新下代码吧，最新提交我关闭了时区。

**Comment by ownerorall** [comment]
我的网址是：www.ownerall.icu <http://www.ownerall.icu/>，我按照教程部署完成，但是网站打开很缓慢，虽然显示页面了但是进度条还是在走，总感觉有什么加载不完，网站是没有访问量的，后台我是用的宝塔面板，显示也没有高的占用率，请指点一下我！

**Comment by liangliangyy** [comment]
我试了下，挺快的，你那边慢可能是因为一些js加载慢，主要是hmathjax的js库，你不需要可以改下代码删了。

**Comment by ownerorall** [comment]
老大，我能加你微信么？ 我是新手小白，现在稍微能用pycharm写点代码其余的都不会，django这个库一头雾水！想向您请教请教一些思路，能给我一些找资料和学习的方向！
