### ISSUE TITLE
新增文章时如果同时指定 tag，保存时会出错

### ISSUE THREAD

**Issue by xmyangz** [liangliangyy/DjangoBlog#77]
出错原因应该是同时写入两张表blog_article和 blog_article_tags，写入顺序错了。估计是先写入blog_article_tags，因为外键不存在而报错。

**Comment by liangliangyy** [comment]
麻烦详细描述下操作过程以及报错信息.

**Comment by xmyangz** [comment]
在本机运行一切正常，推送到 Heroku 服务器就出现新增文章时不能同时加 tag 的 bug，可能是Heroku 服务器的问题，这个 issue 关了吧。
