### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by hemingrujiuhao** [liangliangyy/DjangoBlog#80]
or
    err.raise_mysql_exception(self._data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'djangoblog.accounts_bloguser' doesn't exist")

首先 非常感谢您将项目开源分享了，我想请问一下初始化用户的时候会出现这个错误，也就会在执行这一步的时候（./manage.py createsuperuser），作为一个Java自学Python的朋友万般无赖下请教

**Comment by liangliangyy** [comment]
```
./manage.py makemigrations
./manage.py migrate
```
这两步执行成功了吗?

**Comment by hemingrujiuhao** [comment]
这两步执行成功了，当执行第三步输入用户名的时候会报错，找不到表。当执行程序前我是先是把数据库清空的。


错误信息：


django.db.utils.ProgrammingError: (1146, "Table 'myblog.accounts_bloguser' doesn't exist")
原始邮件
发件人:车亮亮notifications@github.com
收件人:liangliangyy/DjangoBlogDjangoBlog@noreply.github.com
抄送:hemingrujiuhao2639334273@qq.com; Authorauthor@noreply.github.com
发送时间:2018年2月12日(周一) 10:03
主题:Re: [liangliangyy/DjangoBlog] 请教 (#80)


./manage.py makemigrations ./manage.py migrate
这两步执行成功了吗?

**Comment by liangliangyy** [comment]
前面的两步就是为了生成数据库中的表的,你把数据库清空了当然就会报错了.
