### ISSUE TITLE
初始化

### ISSUE THREAD

**Issue by hemingrujiuhao** [liangliangyy/DjangoBlog#81]
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'pagedown',
    'haystack',
    'blog',
    'accounts',
    'comments',
    'oauth',
    'servermanager',
    'compressor'
]

我用那个命令好像无法初始化这里面的所有表

**Comment by liangliangyy** [comment]
参考 #80 中我的回复.
这些是依赖的app,和表没关系,建议先看看官方文档.
