### ISSUE TITLE
No module named 'pagedown'

### ISSUE THREAD

**Issue by tiangeng** [liangliangyy/DjangoBlog#89]
你好，在创建数据库时一直出现ModuleNotFoundError: No module named 'pagedown'，找不到问题出在哪，可否帮忙解释一下，多谢。

**Comment by wjzhangcsu** [comment]
https://stackoverflow.com/questions/18196656/adding-django-pagedown-to-django-1-5-blog-comments

**Comment by liangliangyy** [comment]
`pip install -Ur requirements.txt`
执行了吗

**Comment by tiangeng** [comment]
你好，抱歉才看到回复。pip install -Ur requirements.txt执行过了的，依然报错。搜了一下好像是因为Django2.0不支持pagedown模块了。
感谢百忙之中的回复。
