### ISSUE TITLE
博客的前端显示和楼主的博客前端差的有点多的

### ISSUE THREAD

**Issue by wjzhangcsu** [liangliangyy/DjangoBlog#92]
博客的前端显示和楼主的博客前端差的有点多，是没有把前端放上来吗？如果是这样，能否把前端放上来呢？虽然谁一般网站的灵魂在于数据库，但是在想在github上找个能直接用的博客系统，不是太想取改代码,也不是想用wordpress这种……

**Comment by liangliangyy** [comment]
前端是有放上来的,你说的显示差有点多是什么意思呢?可以提供截图吗?

**Comment by wjzhangcsu** [comment]
@liangliangyy 感谢回复，正在上班，晚上回家提供一下截图。具体的是样式全是乱的，不知道是不是css的问题，我在chrome里面试的。

**Comment by liangliangyy** [comment]
嗯,我在readme里面有说明的.
将settings.py中的DEBUG=False修改为DEBUG=True
试试

**Comment by wjzhangcsu** [comment]
@liangliangyy 好的，确实是这个问题，修改为DEBUG=True就可以跑了，我对于python的django框架不是很 熟悉，请问下这是什么原理呢？

**Comment by liangliangyy** [comment]
可以参见  #15
