### ISSUE TITLE
远程nginx有问题

### ISSUE THREAD

**Issue by wjzhangcsu** [liangliangyy/DjangoBlog#93]
你好，我远程买了云主机，系统是centos,然后配置了nginx，可以正常打开，但是在添加标签和分类的时候会有502,具体错误是：
2018/04/01 23:59:16 [error] 8739#0: *147 upstream prematurely closed connection while reading response header from upstream, client: ****, server: *****, request: "POST /admin/blog/tag/add/ HTTP/1.1", upstream: "http://unix:/installpkg/DjangoBlog/gunicorn.sock:/admin/blog/tag/add/", host: "****", referrer: "http://140.143.152.209/admin/blog/tag/add/"
尝试了很多办法都不能解决，求帮助～

**Comment by wjzhangcsu** [comment]
我的nginx配置如下：
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	default_type  application/octet-stream;
	log_format timed_combined '$remote_addr - $remote_user [$time_local] '
	'"$request" $status $body_bytes_sent '
	'"$http_referer" "$http_user_agent" '
	'$request_time $upstream_response_time $pipe';
	upstream djangoblog_server {
    		server unix:/installpkg/DjangoBlog/gunicorn.sock fail_timeout=60;
	}

server {

    server_name 140.143.152.209;
    root /installpkg/DjangoBlog;

    listen 80;

    keepalive_timeout 70;
    access_log /var/log/django_access.log;
    error_log /var/log/django_error.log;

    location /static/ {
          expires max;
          alias /installpkg/DjangoBlog/collectedstatic/;
    }

    location / {
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_connect_timeout 75s;
        proxy_read_timeout 300s;


        if (!-f $request_filename) {
            proxy_pass http://djangoblog_server;
            break;
        }
    }

}
}

**Comment by wjzhangcsu** [comment]
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	default_type  application/octet-stream;
	log_format timed_combined '$remote_addr - $remote_user [$time_local] '
	'"$request" $status $body_bytes_sent '
	'"$http_referer" "$http_user_agent" '
	'$request_time $upstream_response_time $pipe';
	upstream djangoblog_server {
    		server unix:/installpkg/DjangoBlog/gunicorn.sock fail_timeout=60;
	}

server {

    server_name _;
    root /installpkg/DjangoBlog;

    listen 80;

    keepalive_timeout 70;
    access_log /var/log/django_access.log;
    error_log /var/log/django_error.log;

    location /static/ {
          expires max;
          alias /installpkg/DjangoBlog/collectedstatic/;
    }

    location / {
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_connect_timeout 75s;
        proxy_read_timeout 300s;


        if (!-f $request_filename) {
            proxy_pass http://djangoblog_server;
            break;
        }
    }

}
}

**Comment by wjzhangcsu** [comment]
使用的腾讯云，不用反响代理的话没有问题

**Comment by liangliangyy** [comment]
后端代码有报错吗?能贴下后端代码的报错信息吗?

**Comment by wjzhangcsu** [comment]
后端代码没有报错

**Comment by wjzhangcsu** [comment]
我试了gunicorn和uwsgi，添加分类和添加标签都不行，但是添加友情链接就可以，本地跑的话是都可以的，应该是代理的问题了，但是还是找不到具体是哪里出了问题。

**Comment by liangliangyy** [comment]
可以参考下我的nginx配置
```
upstream djangoblog_server {
	server unix:/var/www/DjangoBlog/run/gunicorn.sock fail_timeout=0;
	keepalive 80;
}

server {
	#其他配置...
	location ^~ /admin/ {
		proxy_http_version       1.1;

		add_header               Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";

		add_header               X-Frame-Options DENY;

		add_header               X-Content-Type-Options nosniff;
		proxy_set_header Host $http_host;
		proxy_redirect off;

		proxy_set_header         X-Forwarded-For  $proxy_add_x_forwarded_for;
		if (!-f $request_filename) {
				proxy_pass http://djangoblog_server;			
				break;
		}

	}

	location / {

		# proxy_set_header X-Forwarded-Proto https;

		proxy_set_header Host $http_host;
		proxy_redirect off;

		# proxy_buffering off;

		# Try to serve static files from nginx, no point in making an
		# *application* server like Unicorn/Rainbows! serve static files.

		if (!-f $request_filename) {
				proxy_pass http://djangoblog_server;					
				break;
		}
	}

}

```

**Comment by wjzhangcsu** [comment]
好的，感谢～～～～～～

**Comment by wjzhangcsu** [comment]
我刚刚试了这个配置，也不行，话说那个其他配置那里省略了很多东西阿，能不能贴出来让我试试呢？这个配置连静态文件都没有…

**Comment by wjzhangcsu** [comment]
虽然我现在有点怀疑是腾讯云的问题，但是具体也不知道是什么问题，我试了ubuntu和centos，都是报一样的错误。然后试了uwsgi和gunicorn，报错不一样但是差不多是一个意思，都是上游的问题，我看了django的代码，发现分类和标签是有用缓存的，不知道是不是和这个有关系。另外，前端页面也有个小bug,就是回复评论的评论时，回复框会错位～请留意
